/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CommunityIntakeAssertionDisposition = "incorporated" | "not_incorporated" | "not_selected" | "pending" | "selected" | "superseded";

export type CommunityIntakeAttachmentState = "clean" | "deleted" | "infected" | "quarantined" | "scan_failed";

export type CommunityIntakeContributorStatus = "accepted" | "action_required" | "draft" | "duplicate" | "expired" | "incorporated_full" | "incorporated_partial" | "incorporation_in_progress" | "not_accepted" | "out_of_scope" | "submitted" | "target_merged" | "target_unpublished" | "withdrawn";

export type CommunityIntakeSourceKind = "document" | "other" | "publication" | "url";

export type CommunityIntakeSubmissionState = "closed" | "draft" | "expired" | "submitted" | "withdrawn";

export type CommunityIntakeSubmissionType = "correction" | "sourced_information";

export type CommunityIntakeTargetType = "panda";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CommunityIntakeAttachments {
  attachment_id: Generated<string>;
  body_deleted_at: Timestamp | null;
  bound_revision_number: number | null;
  byte_size: Int8;
  content_sha256: string | null;
  created_at: Generated<Timestamp>;
  last_scan_code: string | null;
  last_scanned_at: Timestamp | null;
  media_type: string;
  metadata_stripped: Generated<boolean>;
  object_version: string | null;
  original_filename: string;
  preview_object_key: string | null;
  scan_attempts: Generated<number>;
  state: Generated<CommunityIntakeAttachmentState>;
  storage_bucket: Generated<string>;
  storage_object_key: string;
  submission_id: string;
  updated_at: Generated<Timestamp>;
  upload_completed_at: Timestamp | null;
}

export interface CommunityIntakeAttachmentScanEvents {
  attachment_id: string;
  attempt_number: number;
  correlation_id: string;
  metadata_stripped: Generated<boolean>;
  outcome: CommunityIntakeAttachmentState;
  preview_object_key: string | null;
  result_code: string;
  scan_event_id: Generated<string>;
  scanned_at: Generated<Timestamp>;
  scanner_name: string;
  scanner_version: string | null;
}

export interface CommunityIntakeAuditEvents {
  actor_subject_hash: string;
  audit_event_id: Generated<string>;
  correlation_id: string;
  details: Generated<Json>;
  event_type: string;
  idempotency_key: string;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  reason: string | null;
  submission_id: string | null;
  target_id: string;
  target_type: string;
}

export interface CommunityIntakeContributorAssertionResults {
  assertion_key: string;
  created_at: Generated<Timestamp>;
  disposition: CommunityIntakeAssertionDisposition;
  explanation: string | null;
  public_reference_id: string | null;
  result_id: Generated<string>;
  revision_number: number;
  status_event_id: string;
  submission_id: string;
}

export interface CommunityIntakeContributorJourneyEvents {
  contributor_subject_hash: string;
  correlation_id: string;
  details: Generated<Json>;
  event_type: string;
  journey_event_id: Generated<string>;
  locale: string | null;
  occurred_at: Generated<Timestamp>;
  submission_id: string | null;
}

export interface CommunityIntakeContributorStatusEvents {
  action_required_fields: Generated<Json>;
  active_revision_number: number | null;
  actor_subject_hash: string;
  correlation_id: string;
  idempotency_key: string;
  occurred_at: Generated<Timestamp>;
  source_context: string;
  source_event_id: string | null;
  status: CommunityIntakeContributorStatus;
  status_event_id: Generated<string>;
  submission_id: string;
  target_redirect_id: string | null;
  user_visible_reason: string | null;
}

export interface CommunityIntakeRetentionEvents {
  action: string;
  contributor_subject_hash: string;
  correlation_id: string;
  details: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  reason: string;
  retention_event_id: Generated<string>;
  submission_id: string | null;
}

export interface CommunityIntakeSensitiveReadEvents {
  actor_subject_hash: string;
  attachment_id: string;
  correlation_id: string;
  denial_reason: string | null;
  outcome: string;
  purpose: string;
  read_at: Generated<Timestamp>;
  read_event_id: Generated<string>;
  reference_expires_at: Timestamp | null;
  reference_jti_hash: string | null;
}

export interface CommunityIntakeSubmissionRevisions {
  content: Json;
  content_sha256: string;
  public_version_seen: string;
  revision_number: number;
  submission_id: string;
  submitted_at: Generated<Timestamp>;
}

export interface CommunityIntakeSubmissions {
  account_id: string | null;
  anonymized_at: Timestamp | null;
  closed_at: Timestamp | null;
  contributor_status: Generated<CommunityIntakeContributorStatus>;
  contributor_status_updated_at: Generated<Timestamp>;
  contributor_subject_anonymization_request_id: string | null;
  contributor_subject_anonymized_at: Timestamp | null;
  contributor_subject_hash: string;
  created_at: Generated<Timestamp>;
  current_status_event_id: string | null;
  draft_content: Generated<Json>;
  expires_at: Generated<Timestamp>;
  latest_revision_number: Generated<number>;
  public_version_seen: string;
  retention_completed_at: Timestamp | null;
  retention_due_at: Timestamp | null;
  state: Generated<CommunityIntakeSubmissionState>;
  submission_id: Generated<string>;
  submission_type: CommunityIntakeSubmissionType;
  submitted_at: Timestamp | null;
  target_id: string;
  target_type: Generated<CommunityIntakeTargetType>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  withdrawn_at: Timestamp | null;
}

export interface CommunityIntakeSubmittedSources {
  created_at: Generated<Timestamp>;
  locator: string;
  normalized_locator_hash: string;
  published_on: string | null;
  publisher: string | null;
  revision_number: number;
  source_id: Generated<string>;
  source_kind: CommunityIntakeSourceKind;
  submission_id: string;
  title: string;
}

export interface DB {
  "community_intake.attachment_scan_events": CommunityIntakeAttachmentScanEvents;
  "community_intake.attachments": CommunityIntakeAttachments;
  "community_intake.audit_events": CommunityIntakeAuditEvents;
  "community_intake.contributor_assertion_results": CommunityIntakeContributorAssertionResults;
  "community_intake.contributor_journey_events": CommunityIntakeContributorJourneyEvents;
  "community_intake.contributor_status_events": CommunityIntakeContributorStatusEvents;
  "community_intake.retention_events": CommunityIntakeRetentionEvents;
  "community_intake.sensitive_read_events": CommunityIntakeSensitiveReadEvents;
  "community_intake.submission_revisions": CommunityIntakeSubmissionRevisions;
  "community_intake.submissions": CommunityIntakeSubmissions;
  "community_intake.submitted_sources": CommunityIntakeSubmittedSources;
}
