/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface UpdatesItems {
  correlation_id: string;
  occurred_at: Timestamp;
  previous_release_id: string | null;
  published_at: Generated<Timestamp>;
  release_id: string;
  release_version: string;
  source_event_id: string;
  update_id: Generated<string>;
  update_type: string;
}

export interface UpdatesTargets {
  change_type: string;
  resource_id: string;
  resource_kind: string;
  update_id: string;
}

export interface DB {
  "updates.items": UpdatesItems;
  "updates.targets": UpdatesTargets;
}
