/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CommunityIntakeContributorStatus = "accepted" | "action_required" | "draft" | "duplicate" | "expired" | "incorporated_full" | "incorporated_partial" | "incorporation_in_progress" | "not_accepted" | "out_of_scope" | "submitted" | "target_merged" | "target_unpublished" | "withdrawn";

export type CommunityIntakeTargetType = "panda";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type ReviewModerationAppealDecisionOutcome = "dismissed" | "modified" | "overturned" | "upheld";

export type ReviewModerationAppealState = "closed" | "open" | "under_review";

export type ReviewModerationReviewCaseState = "assigned" | "closed" | "decision_ready" | "incorporation_recommended" | "new" | "triage" | "waiting";

export type ReviewModerationReviewDecisionOutcome = "abuse" | "accepted" | "duplicate" | "not_accepted" | "out_of_scope";

export type ReviewModerationSanctionKind = "account_closed_for_abuse" | "account_suspended" | "attachment_restricted" | "notification_restricted" | "submission_restricted" | "warning";

export type ReviewModerationSanctionScope = "account" | "attachment" | "notification" | "submission";

export type ReviewModerationSourceVerificationOutcome = "rejected" | "verified";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ReviewModerationAppealCases {
  account_id: string;
  appeal_case_id: Generated<string>;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  first_responded_at: Timestamp | null;
  first_response_due_at: Generated<Timestamp>;
  sanction_id: string;
  state: Generated<ReviewModerationAppealState>;
  updated_at: Generated<Timestamp>;
  user_statement: string;
  version: Generated<number>;
}

export interface ReviewModerationAppealDecisions {
  appeal_case_id: string;
  decided_at: Generated<Timestamp>;
  decided_by_account_id: string;
  decision_id: Generated<string>;
  internal_explanation: string;
  outcome: ReviewModerationAppealDecisionOutcome;
  user_visible_explanation: string;
}

export interface ReviewModerationAppealQueue {
  account_id: string | null;
  age_seconds: Int8 | null;
  appeal_case_id: string | null;
  appeal_sla_overdue: boolean | null;
  closed_at: Timestamp | null;
  created_at: Timestamp | null;
  first_responded_at: Timestamp | null;
  first_response_due_at: Timestamp | null;
  sanction_id: string | null;
  state: ReviewModerationAppealState | null;
  updated_at: Timestamp | null;
  user_statement: string | null;
  version: number | null;
}

export interface ReviewModerationAuditEvents {
  actor_account_id: string | null;
  audit_event_id: Generated<string>;
  correlation_id: string;
  details: Generated<Json>;
  event_type: string;
  idempotency_key: string | null;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  reason: string | null;
  review_case_id: string | null;
  submission_id: string | null;
}

export interface ReviewModerationCommandReceipts {
  actor_account_id: string;
  command_name: string;
  created_at: Generated<Timestamp>;
  idempotency_key: string;
  receipt_id: Generated<string>;
  review_case_id: string | null;
}

export interface ReviewModerationCurationRecommendations {
  assertion_key: string;
  decision_id: string;
  reason: string;
  recommendation_id: Generated<string>;
  recommended_at: Generated<Timestamp>;
  recommended_by_account_id: string;
  review_case_id: string;
}

export interface ReviewModerationDecisions {
  active_revision_number: number;
  decided_at: Generated<Timestamp>;
  decided_by_account_id: string;
  decision_id: Generated<string>;
  duplicate_of_review_case_id: string | null;
  internal_reason: string | null;
  outcome: ReviewModerationReviewDecisionOutcome;
  review_case_id: string;
  selected_assertion_keys: Generated<Json>;
  user_visible_explanation: string;
}

export interface ReviewModerationInformationRequests {
  active_revision_number: number;
  created_at: Generated<Timestamp>;
  information_request_id: Generated<string>;
  internal_note: string | null;
  requested_by_account_id: string;
  requested_fields: Json;
  review_case_id: string;
  user_visible_message: string;
}

export interface ReviewModerationModerationAlerts {
  alert_type: string | null;
  subject_id: string | null;
}

export interface ReviewModerationModerationAuditEvents {
  account_id: string | null;
  actor_account_id: string | null;
  appeal_case_id: string | null;
  audit_event_id: Generated<string>;
  correlation_id: string;
  details: Generated<Json>;
  event_type: string;
  idempotency_key: string | null;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  reason: string | null;
  sanction_id: string | null;
}

export interface ReviewModerationModerationCommandReceipts {
  actor_account_id: string;
  command_name: string;
  created_at: Generated<Timestamp>;
  idempotency_key: string;
  receipt_id: Generated<string>;
  request_fingerprint: string;
  result_id: string;
  result_type: string;
}

export interface ReviewModerationModerationSubjects {
  account_closed_for_abuse: Generated<boolean>;
  account_id: string;
  account_restricted_until: Timestamp | null;
  account_sanction_id: string | null;
  account_suspended: Generated<boolean>;
  attachment_restricted: Generated<boolean>;
  attachment_restricted_until: Timestamp | null;
  attachment_sanction_id: string | null;
  created_at: Generated<Timestamp>;
  latest_warning_at: Timestamp | null;
  notification_restricted: Generated<boolean>;
  notification_restricted_until: Timestamp | null;
  notification_sanction_id: string | null;
  repeat_abuse_count: Generated<number>;
  submission_restricted: Generated<boolean>;
  submission_restricted_until: Timestamp | null;
  submission_sanction_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  warning_sanction_id: string | null;
}

export interface ReviewModerationModerationSubjectStatus {
  account_closed_for_abuse: boolean | null;
  account_id: string | null;
  account_restricted_until: Timestamp | null;
  account_sanction_id: string | null;
  account_state: string | null;
  account_suspended: boolean | null;
  attachment_restricted: boolean | null;
  attachment_restricted_until: Timestamp | null;
  attachment_sanction_id: string | null;
  created_at: Timestamp | null;
  effective_account_suspended: boolean | null;
  effective_attachment_restricted: boolean | null;
  effective_notification_restricted: boolean | null;
  effective_submission_restricted: boolean | null;
  expired_restriction_projected: boolean | null;
  inconsistent_account_state: boolean | null;
  latest_warning_at: Timestamp | null;
  notification_restricted: boolean | null;
  notification_restricted_until: Timestamp | null;
  notification_sanction_id: string | null;
  repeat_abuse_count: number | null;
  submission_restricted: boolean | null;
  submission_restricted_until: Timestamp | null;
  submission_sanction_id: string | null;
  updated_at: Timestamp | null;
  version: number | null;
  warning_sanction_id: string | null;
}

export interface ReviewModerationRestorationEvents {
  account_id: string;
  correlation_id: string;
  idempotency_key: string;
  internal_explanation: string;
  reason_code: string;
  restoration_id: Generated<string>;
  restored_at: Generated<Timestamp>;
  restored_by_account_id: string;
  sanction_id: string;
  subject_version_after: number;
  subject_version_before: number;
  user_visible_explanation: string;
}

export interface ReviewModerationReviewCaseQueue {
  active_revision_number: number | null;
  closed_at: Timestamp | null;
  contributor_status: CommunityIntakeContributorStatus | null;
  created_at: Timestamp | null;
  duplicate_of_review_case_id: string | null;
  first_responded_at: Timestamp | null;
  first_response_due_at: Timestamp | null;
  opened_revision_number: number | null;
  primary_assignee_id: string | null;
  queue_age_seconds: Int8 | null;
  reopened_from_review_case_id: string | null;
  review_case_id: string | null;
  risk_level: string | null;
  sla_overdue: boolean | null;
  state: ReviewModerationReviewCaseState | null;
  submission_id: string | null;
  target_id: string | null;
  target_type: CommunityIntakeTargetType | null;
  updated_at: Timestamp | null;
  version: number | null;
}

export interface ReviewModerationReviewCases {
  active_revision_number: number;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  duplicate_of_review_case_id: string | null;
  first_responded_at: Timestamp | null;
  first_response_due_at: Generated<Timestamp>;
  opened_revision_number: number;
  primary_assignee_id: string | null;
  reopened_from_review_case_id: string | null;
  review_case_id: Generated<string>;
  risk_level: Generated<string>;
  state: Generated<ReviewModerationReviewCaseState>;
  submission_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ReviewModerationSanctions {
  account_id: string;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  ends_at: Timestamp | null;
  idempotency_key: string;
  internal_explanation: string;
  issued_by_account_id: string;
  kind: ReviewModerationSanctionKind;
  reason_code: string;
  sanction_id: Generated<string>;
  scope: ReviewModerationSanctionScope;
  starts_at: Timestamp;
  subject_version_after: number;
  subject_version_before: number;
  user_visible_explanation: string;
}

export interface ReviewModerationSlaAlerts {
  active_revision_number: number | null;
  closed_at: Timestamp | null;
  contributor_status: CommunityIntakeContributorStatus | null;
  created_at: Timestamp | null;
  duplicate_of_review_case_id: string | null;
  first_responded_at: Timestamp | null;
  first_response_due_at: Timestamp | null;
  opened_revision_number: number | null;
  primary_assignee_id: string | null;
  queue_age_seconds: Int8 | null;
  reopened_from_review_case_id: string | null;
  review_case_id: string | null;
  risk_level: string | null;
  sla_overdue: boolean | null;
  state: ReviewModerationReviewCaseState | null;
  submission_id: string | null;
  target_id: string | null;
  target_type: CommunityIntakeTargetType | null;
  updated_at: Timestamp | null;
  version: number | null;
}

export interface ReviewModerationSourceVerifications {
  active_revision_number: number;
  canonical_source_id: string | null;
  normalized_locator: string | null;
  outcome: ReviewModerationSourceVerificationOutcome;
  reason: string;
  review_case_id: string;
  source_id: string;
  source_verification_id: Generated<string>;
  verified_at: Generated<Timestamp>;
  verified_by_account_id: string;
}

export interface DB {
  "review_moderation.appeal_cases": ReviewModerationAppealCases;
  "review_moderation.appeal_decisions": ReviewModerationAppealDecisions;
  "review_moderation.appeal_queue": ReviewModerationAppealQueue;
  "review_moderation.audit_events": ReviewModerationAuditEvents;
  "review_moderation.command_receipts": ReviewModerationCommandReceipts;
  "review_moderation.curation_recommendations": ReviewModerationCurationRecommendations;
  "review_moderation.decisions": ReviewModerationDecisions;
  "review_moderation.information_requests": ReviewModerationInformationRequests;
  "review_moderation.moderation_alerts": ReviewModerationModerationAlerts;
  "review_moderation.moderation_audit_events": ReviewModerationModerationAuditEvents;
  "review_moderation.moderation_command_receipts": ReviewModerationModerationCommandReceipts;
  "review_moderation.moderation_subject_status": ReviewModerationModerationSubjectStatus;
  "review_moderation.moderation_subjects": ReviewModerationModerationSubjects;
  "review_moderation.restoration_events": ReviewModerationRestorationEvents;
  "review_moderation.review_case_queue": ReviewModerationReviewCaseQueue;
  "review_moderation.review_cases": ReviewModerationReviewCases;
  "review_moderation.sanctions": ReviewModerationSanctions;
  "review_moderation.sla_alerts": ReviewModerationSlaAlerts;
  "review_moderation.source_verifications": ReviewModerationSourceVerifications;
}
