/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PrivacyExportSnapshots {
  account_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  payload: Json;
  request_id: string;
}

export interface PrivacySubjectRequestEvents {
  correlation_id: string;
  error_code: string | null;
  event_id: Generated<string>;
  event_type: string;
  next_state: string;
  occurred_at: Generated<Timestamp>;
  previous_state: string | null;
  request_id: string;
}

export interface PrivacySubjectRequests {
  account_id: string;
  completed_at: Timestamp | null;
  correlation_id: string;
  failed_at: Timestamp | null;
  failure_code: string | null;
  idempotency_key: string;
  kind: string;
  reason: string;
  request_id: Generated<string>;
  requested_at: Generated<Timestamp>;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PrivacySubjectRequestSteps {
  attempts: Generated<number>;
  last_error_code: string | null;
  participant_key: string;
  request_id: string;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "privacy.export_snapshots": PrivacyExportSnapshots;
  "privacy.subject_request_events": PrivacySubjectRequestEvents;
  "privacy.subject_request_steps": PrivacySubjectRequestSteps;
  "privacy.subject_requests": PrivacySubjectRequests;
}
