/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface GameAttempts {
  account_id: string;
  attempt_id: Generated<string>;
  attempted_at: Generated<Timestamp>;
  correct: boolean;
  question_id: string;
  selected_panda_id: string;
}

export interface GameQuestions {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  difficulty: string;
  media_asset_id: string;
  option_panda_ids: string[];
  published_at: Timestamp | null;
  question_id: Generated<string>;
  recognition_tips: Generated<Json>;
  state: Generated<string>;
  target_panda_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface DB {
  "game.attempts": GameAttempts;
  "game.questions": GameQuestions;
}
