/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface NotificationChannelPreferences {
  account_id: string;
  category: string;
  channel: string;
  enabled: boolean;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface NotificationMessageChannels {
  channel: string;
  message_id: string;
  state: string;
  suppression_reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface NotificationMessages {
  account_id: string;
  category: string;
  content: Json;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  message_id: Generated<string>;
  read_at: Timestamp | null;
  seen_at: Timestamp | null;
  source_event_id: string;
}

export interface NotificationProviderAttempts {
  attempt_id: Generated<string>;
  attempt_number: number;
  error_code: string | null;
  job_id: string;
  latency_ms: number;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  provider: string;
  provider_message_id: string | null;
  retryable: boolean;
}

export interface NotificationProviderDeadLetters {
  attempt_count: number;
  dead_lettered_at: Generated<Timestamp>;
  final_error_code: string;
  job_id: string;
}

export interface NotificationProviderJobs {
  attempt_count: Generated<number>;
  channel: Generated<string>;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  dead_lettered_at: Timestamp | null;
  job_id: Generated<string>;
  last_error_code: string | null;
  message_id: string;
  next_attempt_at: Generated<Timestamp>;
  provider: string | null;
  provider_message_id: string | null;
  state: Generated<string>;
  submitted_at: Timestamp | null;
  suppressed_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "notification.channel_preferences": NotificationChannelPreferences;
  "notification.message_channels": NotificationMessageChannels;
  "notification.messages": NotificationMessages;
  "notification.provider_attempts": NotificationProviderAttempts;
  "notification.provider_dead_letters": NotificationProviderDeadLetters;
  "notification.provider_jobs": NotificationProviderJobs;
}
