/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CurationApprovalDecisions {
  approval_id: Generated<string>;
  change_set_id: string;
  decided_at: Generated<Timestamp>;
  decided_by_account_id: string;
  decision: string;
  reason: string;
}

export interface CurationChangeSets {
  applied_at: Timestamp | null;
  approved_at: Timestamp | null;
  approved_by_account_id: string | null;
  change_set_id: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by_account_id: string;
  origin_decision_id: string;
  origin_review_case_id: string;
  origin_revision_number: number;
  origin_submission_id: string;
  reason: string;
  state: Generated<string>;
  target_panda_id: string;
  updated_at: Generated<Timestamp>;
  validated_at: Timestamp | null;
  validated_by_account_id: string | null;
  version: Generated<number>;
}

export interface CurationPandaFactChanges {
  applied_assertion_id: string | null;
  certainty: string;
  change_id: Generated<string>;
  change_set_id: string;
  created_at: Generated<Timestamp>;
  field_key: string;
  last_verified_on: string;
  origin_assertion_key: string;
  proposed_value: Json;
  source_ids: string[];
}

export interface DB {
  "curation.approval_decisions": CurationApprovalDecisions;
  "curation.change_sets": CurationChangeSets;
  "curation.panda_fact_changes": CurationPandaFactChanges;
}
