/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type NotificationCategory = "birthday" | "correction_retraction" | "incorporation" | "major_activity" | "security_role" | "submission_status";

export type NotificationChannel = "email" | "station" | "web_push";

export type NotificationDeliveryState = "delivered" | "failed" | "pending" | "queued" | "retracted" | "suppressed";

export type NotificationDigestFrequency = "daily" | "weekly";

export type NotificationDigestState = "building" | "delivered" | "failed" | "queued" | "retracted";

export type NotificationIntentState = "active" | "retracted";

export type NotificationTransportJobState = "dead_lettered" | "delivered" | "failed" | "pending" | "queued" | "retrying" | "submitted" | "suppressed";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface NotificationAuditEvents {
  actor_subject_hash: string | null;
  audit_id: Generated<string>;
  correlation_id: string;
  details: Generated<Json>;
  event_type: string;
  idempotency_key: string;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  reason: string | null;
  subject_account_hash: string | null;
  target_id: string;
  target_type: string;
}

export interface NotificationChannelPreferences {
  account_id: string;
  category: string;
  channel: string;
  enabled: boolean;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface NotificationDeliveryAttempts {
  attempt_id: Generated<string>;
  attempt_number: number;
  attempted_at: Generated<Timestamp>;
  channel: NotificationChannel;
  correlation_id: string;
  failure_code: string | null;
  failure_detail: string | null;
  idempotency_key: string;
  intent_id: string;
  provider: string | null;
  provider_message_id: string | null;
  state: NotificationDeliveryState;
}

export interface NotificationDeliveryJobs {
  account_id: string;
  attempt_count: Generated<number>;
  attempt_cycle_start: Generated<number>;
  channel: Generated<NotificationChannel>;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  dead_lettered_at: Timestamp | null;
  delivered_at: Timestamp | null;
  delivery_id: string;
  digest_batch_id: string | null;
  failed_at: Timestamp | null;
  intent_id: string | null;
  last_error_at: Timestamp | null;
  last_error_code: string | null;
  locale: string;
  next_attempt_at: Timestamp | null;
  provider: string | null;
  provider_message_id: string | null;
  queue_message_id: Int8 | null;
  queued_at: Timestamp | null;
  source_event_id: string;
  state: Generated<NotificationTransportJobState>;
  suppressed_at: Timestamp | null;
  template_key: string;
  template_version: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface NotificationDigestBatches {
  account_id: string;
  batch_id: Generated<string>;
  content: Json;
  content_version: Generated<number>;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  failed_at: Timestamp | null;
  frequency: NotificationDigestFrequency;
  idempotency_key: string;
  locale: string;
  period_end: Timestamp;
  period_start: Timestamp;
  queued_at: Timestamp | null;
  retracted_at: Timestamp | null;
  state: Generated<NotificationDigestState>;
}

export interface NotificationDigestItems {
  batch_id: string;
  content_snapshot: Json;
  intent_id: string;
  ordinal: number;
}

export interface NotificationEmailSuppressions {
  account_id: string;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  provider_event_id: string;
  reason: string;
}

export interface NotificationInboxItems {
  account_id: string;
  body: Json;
  body_expires_at: Generated<Timestamp>;
  body_purged_at: Timestamp | null;
  body_version: Generated<number>;
  category: NotificationCategory;
  created_at: Generated<Timestamp>;
  inbox_item_id: Generated<string>;
  intent_id: string;
  read_at: Timestamp | null;
  retracted_at: Timestamp | null;
  retraction_reason: string | null;
  seen_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface NotificationInboxStateEvents {
  account_subject_hash: string;
  action: string;
  affected_count: Generated<number>;
  correlation_id: string;
  idempotency_key: string;
  inbox_item_id: string | null;
  occurred_at: Generated<Timestamp>;
  state_event_id: Generated<string>;
}

export interface NotificationIntentChannels {
  channel: NotificationChannel;
  decided_at: Generated<Timestamp>;
  decision: string;
  delivered_at: Timestamp | null;
  delivery_state: NotificationDeliveryState;
  enabled: boolean;
  failed_at: Timestamp | null;
  intent_id: string;
  preference_version: number | null;
  queued_at: Timestamp | null;
  suppression_reason: string | null;
}

export interface NotificationIntents {
  account_id: string;
  audience_snapshot: Json;
  category: NotificationCategory;
  content_snapshot: Json;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  intent_id: Generated<string>;
  logical_key: string;
  mandatory: Generated<boolean>;
  preference_snapshot: Json;
  retracted_at: Timestamp | null;
  retraction_reason: string | null;
  source_context: string;
  source_event_id: string;
  source_event_type: string;
  source_id: string;
  source_version: number | null;
  state: Generated<NotificationIntentState>;
}

export interface NotificationMessageChannels {
  channel: string;
  message_id: string;
  state: string;
  suppression_reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface NotificationMessages {
  account_id: string;
  category: string;
  content: Json;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  message_id: Generated<string>;
  read_at: Timestamp | null;
  seen_at: Timestamp | null;
  source_event_id: string;
}

export interface NotificationPreferenceEvents {
  account_subject_hash: string;
  category: NotificationCategory;
  channel: NotificationChannel;
  correlation_id: string;
  enabled: boolean;
  event_id: Generated<string>;
  idempotency_key: string;
  occurred_at: Generated<Timestamp>;
  preference_version: number;
}

export interface NotificationPreferences {
  account_id: string;
  category: NotificationCategory;
  channel: NotificationChannel;
  enabled: boolean;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface NotificationProviderAttempts {
  attempt_id: Generated<string>;
  attempt_number: number;
  error_code: string | null;
  job_id: string;
  latency_ms: number;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  provider: string;
  provider_message_id: string | null;
  retryable: boolean;
}

export interface NotificationProviderDeadLetters {
  attempt_count: number;
  dead_lettered_at: Generated<Timestamp>;
  final_error_code: string;
  job_id: string;
}

export interface NotificationProviderJobs {
  attempt_count: Generated<number>;
  channel: Generated<string>;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  dead_lettered_at: Timestamp | null;
  job_id: Generated<string>;
  last_error_code: string | null;
  message_id: string;
  next_attempt_at: Generated<Timestamp>;
  provider: string | null;
  provider_message_id: string | null;
  state: Generated<string>;
  submitted_at: Timestamp | null;
  suppressed_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface NotificationProviderWebhookEvents {
  correlation_id: string;
  event_type: string;
  minimal_payload: Generated<Json>;
  outcome: Generated<string>;
  payload_hash: string;
  processed_at: Timestamp | null;
  provider: string;
  provider_event_id: string;
  provider_message_id: string | null;
  received_at: Generated<Timestamp>;
  signature_verified: boolean;
}

export interface NotificationSourceReceipts {
  correlation_id: string;
  event_type: string;
  intent_count: Generated<number>;
  outcome: string;
  payload_hash: string;
  processed_at: Generated<Timestamp>;
  source_event_id: string;
  suppression_reason: string | null;
}

export interface NotificationTransportAttempts {
  attempt_number: number;
  correlation_id: string;
  delivery_id: string;
  failure_code: string | null;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  provider: string;
  provider_latency_ms: number;
  provider_message_id: string | null;
  retryable: Generated<boolean>;
  transport_attempt_id: Generated<string>;
}

export interface NotificationTransportOutboxReceipts {
  correlation_id: string;
  delivery_id: string | null;
  event_type: string;
  outcome: string;
  processed_at: Generated<Timestamp>;
  queue_message_id: Int8 | null;
  reason: string | null;
  source_event_id: string;
}

export interface NotificationWorkerEvents {
  attempt_number: number | null;
  correlation_id: string;
  delivery_id: string | null;
  details: Generated<Json>;
  event_type: string;
  occurred_at: Generated<Timestamp>;
  queue_message_id: Int8 | null;
  queue_name: string;
  reason: string;
  worker_event_id: Generated<string>;
}

export interface DB {
  "notification.audit_events": NotificationAuditEvents;
  "notification.channel_preferences": NotificationChannelPreferences;
  "notification.delivery_attempts": NotificationDeliveryAttempts;
  "notification.delivery_jobs": NotificationDeliveryJobs;
  "notification.digest_batches": NotificationDigestBatches;
  "notification.digest_items": NotificationDigestItems;
  "notification.email_suppressions": NotificationEmailSuppressions;
  "notification.inbox_items": NotificationInboxItems;
  "notification.inbox_state_events": NotificationInboxStateEvents;
  "notification.intent_channels": NotificationIntentChannels;
  "notification.intents": NotificationIntents;
  "notification.message_channels": NotificationMessageChannels;
  "notification.messages": NotificationMessages;
  "notification.preference_events": NotificationPreferenceEvents;
  "notification.preferences": NotificationPreferences;
  "notification.provider_attempts": NotificationProviderAttempts;
  "notification.provider_dead_letters": NotificationProviderDeadLetters;
  "notification.provider_jobs": NotificationProviderJobs;
  "notification.provider_webhook_events": NotificationProviderWebhookEvents;
  "notification.source_receipts": NotificationSourceReceipts;
  "notification.transport_attempts": NotificationTransportAttempts;
  "notification.transport_outbox_receipts": NotificationTransportOutboxReceipts;
  "notification.worker_events": NotificationWorkerEvents;
}
