/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IdentityAccountState = "active" | "deleted" | "deleting" | "suspended";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface IdentityAccounts {
  account_id: string;
  created_at: Generated<Timestamp>;
  email: string | null;
  last_authenticated_at: Timestamp | null;
  last_authentication_method: string | null;
  last_jwt_issued_at: Timestamp | null;
  last_seen_at: Generated<Timestamp>;
  last_session_id: string | null;
  state: Generated<IdentityAccountState>;
  state_changed_at: Generated<Timestamp>;
  state_reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface IdentityAccountStateEvents {
  account_id: string;
  actor_account_id: string | null;
  correlation_id: string;
  event_id: Generated<string>;
  idempotency_key: string;
  next_state: IdentityAccountState;
  occurred_at: Generated<Timestamp>;
  previous_state: IdentityAccountState;
  reason: string;
}

export interface IdentityAuthorizationAuditEvents {
  actor_account_id: string | null;
  assignment_id: string | null;
  audit_id: Generated<string>;
  capability_key: string | null;
  correlation_id: string;
  details: Generated<Json>;
  event_type: string;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  reason: string | null;
  role_key: string | null;
  subject_account_id: string | null;
}

export interface IdentityCapabilities {
  capability_key: string;
  created_at: Generated<Timestamp>;
  description: string;
  minimum_aal: Generated<string>;
  requires_live_session: Generated<boolean>;
  requires_recent_auth: Generated<boolean>;
  sensitive: Generated<boolean>;
}

export interface IdentityProfiles {
  account_id: string;
  bio: Generated<string>;
  nickname: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface IdentityRoleAssignmentRevocations {
  assignment_id: string;
  correlation_id: string;
  idempotency_key: string;
  reason: string;
  revocation_id: Generated<string>;
  revoked_at: Generated<Timestamp>;
  revoked_by_account_id: string | null;
}

export interface IdentityRoleAssignments {
  account_id: string;
  assigned_at: Generated<Timestamp>;
  assigned_by_account_id: string | null;
  assignment_id: Generated<string>;
  correlation_id: string;
  expires_at: Timestamp | null;
  idempotency_key: string;
  reason: string;
  role_key: string;
  source: Generated<string>;
}

export interface IdentityRoleCapabilities {
  capability_key: string;
  created_at: Generated<Timestamp>;
  role_key: string;
}

export interface IdentityRoles {
  created_at: Generated<Timestamp>;
  description: string;
  display_name: string;
  is_staff: Generated<boolean>;
  role_key: string;
}

export interface DB {
  "identity.account_state_events": IdentityAccountStateEvents;
  "identity.accounts": IdentityAccounts;
  "identity.authorization_audit_events": IdentityAuthorizationAuditEvents;
  "identity.capabilities": IdentityCapabilities;
  "identity.profiles": IdentityProfiles;
  "identity.role_assignment_revocations": IdentityRoleAssignmentRevocations;
  "identity.role_assignments": IdentityRoleAssignments;
  "identity.role_capabilities": IdentityRoleCapabilities;
  "identity.roles": IdentityRoles;
}
