/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type PrivacyContextState = "completed" | "failed" | "held" | "not_applicable" | "pending" | "processing";

export type PrivacyExportState = "deleted" | "expired" | "ready";

export type PrivacyHoldState = "active" | "released";

export type PrivacyRequestKind = "access_export" | "account_deletion";

export type PrivacyRequestState = "completed" | "failed" | "processing" | "requested" | "verified";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PrivacyArchiveAnonymizationEvents {
  account_id: string;
  actor_account_id: string;
  contributor_subject_hash: string;
  correlation_id: string;
  counts: Json;
  event_id: Generated<string>;
  idempotency_key: string;
  occurred_at: Generated<Timestamp>;
  request_id: string;
}

export interface PrivacyAuditEvents {
  actor_account_id: string;
  audit_id: Generated<string>;
  correlation_id: string;
  details: Generated<Json>;
  event_type: string;
  idempotency_key: string;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  reason: string | null;
  request_id: string | null;
  subject_account_id: string | null;
}

export interface PrivacyContextEvents {
  actor_account_id: string;
  context_key: string;
  correlation_id: string;
  event_id: Generated<string>;
  idempotency_key: string;
  internal_error_code: string | null;
  next_state: PrivacyContextState;
  occurred_at: Generated<Timestamp>;
  previous_state: PrivacyContextState;
  request_id: string;
}

export interface PrivacyDeletionTombstones {
  account_id: string;
  applied_at: Generated<Timestamp>;
  context_key: string;
  last_replayed_at: Timestamp | null;
  replay_count: Generated<number>;
  request_id: string;
  version: Generated<number>;
}

export interface PrivacyExportArtifacts {
  account_id: string;
  artifact_id: Generated<string>;
  ciphertext: Buffer | null;
  ciphertext_byte_size: Int8 | null;
  ciphertext_sha256: string | null;
  command_hash: string;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  created_by_account_id: string;
  deleted_at: Timestamp | null;
  expired_at: Timestamp | null;
  expires_at: Timestamp;
  idempotency_key: string;
  key_version: Generated<number>;
  nonce: Buffer | null;
  plaintext_byte_size: Int8;
  request_id: string;
  schema_version: Generated<number>;
  state: Generated<PrivacyExportState>;
  version: Generated<number>;
}

export interface PrivacyExportSnapshots {
  account_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  payload: Json;
  request_id: string;
}

export interface PrivacyHoldEvents {
  actor_account_id: string;
  correlation_id: string;
  details: Generated<Json>;
  event_id: Generated<string>;
  event_type: string;
  hold_id: string;
  idempotency_key: string;
  occurred_at: Generated<Timestamp>;
}

export interface PrivacyHolds {
  account_id: string;
  basis: string;
  context_key: string;
  created_at: Generated<Timestamp>;
  created_by_account_id: string;
  hold_id: Generated<string>;
  release_reason: string | null;
  released_at: Timestamp | null;
  released_by_account_id: string | null;
  request_id: string | null;
  review_due_at: Timestamp;
  state: Generated<PrivacyHoldState>;
  version: Generated<number>;
}

export interface PrivacyMaintenanceRuns {
  actor_account_id: string;
  command_hash: string;
  completed_at: Timestamp;
  correlation_id: string;
  counts: Json;
  idempotency_key: string;
  replay_tombstones_after_restore: Generated<boolean>;
  run_id: Generated<string>;
  started_at: Timestamp;
}

export interface PrivacyRequestContexts {
  attempts: Generated<number>;
  context_key: string;
  last_error_code: string | null;
  request_id: string;
  state: Generated<PrivacyContextState>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface PrivacyRequestEvents {
  actor_account_id: string;
  correlation_id: string;
  details: Generated<Json>;
  event_id: Generated<string>;
  event_type: string;
  idempotency_key: string;
  next_state: PrivacyRequestState;
  occurred_at: Generated<Timestamp>;
  previous_state: PrivacyRequestState | null;
  request_id: string;
}

export interface PrivacyRequests {
  account_id: string;
  completed_at: Timestamp | null;
  correlation_id: string;
  failed_at: Timestamp | null;
  failure_code: string | null;
  idempotency_key: string;
  kind: PrivacyRequestKind;
  processing_started_at: Timestamp | null;
  request_id: Generated<string>;
  requested_at: Generated<Timestamp>;
  requested_reason: string;
  state: Generated<PrivacyRequestState>;
  updated_at: Generated<Timestamp>;
  verified_at: Timestamp | null;
  verified_by_account_id: string | null;
  version: Generated<number>;
}

export interface PrivacyRetentionPolicies {
  context_key: string;
  created_at: Generated<Timestamp>;
  created_by_account_id: string | null;
  effective_from: Timestamp;
  enabled: Generated<boolean>;
  policy_key: string;
  rationale: string;
  retention_days: number;
  rolling_backup_days: Generated<number>;
}

export interface PrivacySubjectRequestEvents {
  correlation_id: string;
  error_code: string | null;
  event_id: Generated<string>;
  event_type: string;
  next_state: string;
  occurred_at: Generated<Timestamp>;
  previous_state: string | null;
  request_id: string;
}

export interface PrivacySubjectRequests {
  account_id: string;
  completed_at: Timestamp | null;
  correlation_id: string;
  failed_at: Timestamp | null;
  failure_code: string | null;
  idempotency_key: string;
  kind: string;
  reason: string;
  request_id: Generated<string>;
  requested_at: Generated<Timestamp>;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PrivacySubjectRequestSteps {
  attempts: Generated<number>;
  last_error_code: string | null;
  participant_key: string;
  request_id: string;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "privacy.archive_anonymization_events": PrivacyArchiveAnonymizationEvents;
  "privacy.audit_events": PrivacyAuditEvents;
  "privacy.context_events": PrivacyContextEvents;
  "privacy.deletion_tombstones": PrivacyDeletionTombstones;
  "privacy.export_artifacts": PrivacyExportArtifacts;
  "privacy.export_snapshots": PrivacyExportSnapshots;
  "privacy.hold_events": PrivacyHoldEvents;
  "privacy.holds": PrivacyHolds;
  "privacy.maintenance_runs": PrivacyMaintenanceRuns;
  "privacy.request_contexts": PrivacyRequestContexts;
  "privacy.request_events": PrivacyRequestEvents;
  "privacy.requests": PrivacyRequests;
  "privacy.retention_policies": PrivacyRetentionPolicies;
  "privacy.subject_request_events": PrivacySubjectRequestEvents;
  "privacy.subject_request_steps": PrivacySubjectRequestSteps;
  "privacy.subject_requests": PrivacySubjectRequests;
}
