/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PublicReadEvidenceSources {
  access_state: string;
  evidence_tier: string | null;
  language_tag: string;
  last_verified_on: string;
  public_summary: string | null;
  published_on: string | null;
  publisher: string;
  release_id: string;
  source_id: string;
  title: string;
  url: string;
}

export interface PublicReadInstitutions {
  country_code: string | null;
  institution_id: string;
  name_en: string | null;
  name_zh: string | null;
  release_id: string;
  slug: string;
}

export interface PublicReadLifeEvents {
  event_id: string;
  event_status: string;
  event_type: string;
  from_place_id: string | null;
  occurred_on: string | null;
  occurred_precision: string;
  participant_ids: Generated<string[]>;
  release_id: string;
  source_ids: Generated<string[]>;
  summary: string | null;
  to_place_id: string | null;
}

export interface PublicReadLineage {
  assertion_id: string;
  child_id: string;
  parent_id: string;
  parent_role: string;
  release_id: string;
  source_ids: Generated<string[]>;
}

export interface PublicReadMedia {
  asset_id: string;
  attribution_text: string | null;
  content_sha256: string;
  copyright_text: string | null;
  creator: string | null;
  display_order: number;
  license: string | null;
  media_type: string;
  object_key: string;
  panda_id: string;
  release_id: string;
  source_id: string | null;
  taken_at: Timestamp | null;
  title: string | null;
  usage_role: string;
}

export interface PublicReadPandas {
  canonical_slug: string;
  evidence_source_ids: Generated<string[]>;
  facts: Json;
  legacy_slugs: Generated<string[]>;
  names: Json;
  panda_id: string;
  release_id: string;
}

export interface PublicReadPlaces {
  country_code: string | null;
  institution_id: string | null;
  latitude: number | null;
  longitude: number | null;
  name_en: string | null;
  name_zh: string | null;
  place_id: string;
  place_type: string;
  region: string | null;
  release_id: string;
  slug: string;
}

export interface PublicReadResidencies {
  end_on: string | null;
  end_precision: string | null;
  panda_id: string;
  place_id: string;
  release_id: string;
  residency_id: string;
  residency_type: string;
  source_ids: Generated<string[]>;
  start_on: string | null;
  start_precision: string;
  status: string;
}

export interface PublicReadStats {
  evidence_source_count: number;
  institution_count: number;
  life_event_count: number;
  lineage_count: number;
  media_count: number;
  panda_count: number;
  place_count: number;
  release_id: string;
  residency_count: number;
}

export interface DB {
  "public_read.evidence_sources": PublicReadEvidenceSources;
  "public_read.institutions": PublicReadInstitutions;
  "public_read.life_events": PublicReadLifeEvents;
  "public_read.lineage": PublicReadLineage;
  "public_read.media": PublicReadMedia;
  "public_read.pandas": PublicReadPandas;
  "public_read.places": PublicReadPlaces;
  "public_read.residencies": PublicReadResidencies;
  "public_read.stats": PublicReadStats;
}
