/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EvidenceAttachments {
  attachment_id: Generated<string>;
  byte_size: Int8;
  content_sha256: string;
  created_at: Generated<Timestamp>;
  media_type: string;
  object_version: string;
  source_id: string;
  storage_bucket: string;
  storage_key: string;
}

export interface EvidencePipelineSourceExportV1 {
  access_state: string | null;
  content_sha256: string | null;
  evidence_tier: string | null;
  language_tag: string | null;
  last_verified_on: string | null;
  public_summary: string | null;
  published_on: string | null;
  publisher: string | null;
  source_id: string | null;
  title: string | null;
  url: string | null;
}

export interface EvidenceSources {
  access_state: string;
  content_sha256: string | null;
  created_at: Generated<Timestamp>;
  evidence_tier: string | null;
  internal_notes: string | null;
  language_tag: string;
  last_verified_on: string;
  public_summary: string | null;
  published_on: string | null;
  publisher: string;
  source_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
  url: string;
}

export interface DB {
  "evidence.attachments": EvidenceAttachments;
  "evidence.pipeline_source_export_v1": EvidencePipelineSourceExportV1;
  "evidence.sources": EvidenceSources;
}
