/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface LifeHistoryEventParticipants {
  event_id: string;
  panda_id: string;
  participant_role: Generated<string>;
}

export interface LifeHistoryEvents {
  created_at: Generated<Timestamp>;
  event_id: string;
  event_status: string;
  event_type: string;
  from_place_id: string | null;
  occurred_on: string | null;
  occurred_precision: string;
  summary: string | null;
  to_place_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface LifeHistoryEventSources {
  event_id: string;
  source_id: string;
}

export interface LifeHistoryResidencies {
  created_at: Generated<Timestamp>;
  end_on: string | null;
  end_precision: string | null;
  panda_id: string;
  place_id: string;
  residency_id: string;
  residency_type: string;
  start_on: string | null;
  start_precision: string;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface LifeHistoryResidencySources {
  residency_id: string;
  source_id: string;
}

export interface DB {
  "life_history.event_participants": LifeHistoryEventParticipants;
  "life_history.event_sources": LifeHistoryEventSources;
  "life_history.events": LifeHistoryEvents;
  "life_history.residencies": LifeHistoryResidencies;
  "life_history.residency_sources": LifeHistoryResidencySources;
}
