/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditEvidenceEvents {
  aggregate_id: string;
  aggregate_type: string;
  correlation_id: string;
  event_type: string;
  occurred_at: Timestamp;
  payload_sha256: string;
  recorded_at: Generated<Timestamp>;
  source_context: string;
  source_event_id: string;
}

export interface DB {
  "audit.evidence_events": AuditEvidenceEvents;
}
