/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EngagementCollectionPandas {
  added_at: Generated<Timestamp>;
  collection_id: string;
  panda_id: string;
}

export interface EngagementCollections {
  account_id: string;
  collection_id: Generated<string>;
  created_at: Generated<Timestamp>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface EngagementFavorites {
  account_id: string;
  favorited_at: Generated<Timestamp>;
  panda_id: string;
}

export interface EngagementLocationCheckins {
  account_id: string;
  checkin_id: Generated<string>;
  created_at: Generated<Timestamp>;
  note: string | null;
  place_id: string;
  visited_on: string;
}

export interface EngagementSeenPandas {
  account_id: string;
  first_seen_at: Generated<Timestamp>;
  note: string | null;
  panda_id: string;
  place_id: string | null;
  seen_id: Generated<string>;
  seen_on: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "engagement.collection_pandas": EngagementCollectionPandas;
  "engagement.collections": EngagementCollections;
  "engagement.favorites": EngagementFavorites;
  "engagement.location_checkins": EngagementLocationCheckins;
  "engagement.seen_pandas": EngagementSeenPandas;
}
