/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditEventFacts {
  action: string;
  actor_account_id: string | null;
  actor_role_snapshot: Generated<Json>;
  actor_subject_hash: string | null;
  after_version: string | null;
  before_version: string | null;
  bulk_count: Generated<number>;
  correlation_id: string;
  /**
   * SHA-256 of source-context details; raw source payload is not copied into the projection.
   */
  details_hash: string;
  diff_hash: string | null;
  event_class: Generated<string>;
  event_id: Generated<string>;
  idempotency_key: string | null;
  occurred_at: Timestamp;
  projected_at: Generated<Timestamp>;
  reason: string;
  related_case_id: string | null;
  related_release_id: string | null;
  request_id: string | null;
  result: string;
  sensitive_read: Generated<boolean>;
  source_context: string;
  source_event_id: string;
  subject_account_id: string | null;
  target_id: string;
  target_type: string;
}

export interface AuditEvidenceEvents {
  aggregate_id: string;
  aggregate_type: string;
  correlation_id: string;
  event_type: string;
  occurred_at: Timestamp;
  payload_sha256: string;
  recorded_at: Generated<Timestamp>;
  source_context: string;
  source_event_id: string;
}

export interface AuditExportArtifacts {
  artifact_id: Generated<string>;
  byte_size: number;
  content_type: Generated<string>;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  encrypted_payload: Buffer;
  encryption_algorithm: Generated<string>;
  expires_at: Timestamp;
  /**
   * SHA-256 of the decrypted canonical NDJSON export file.
   */
  file_sha256: string;
  generated_by_account_id: string;
  idempotency_key: string;
  key_version: Generated<number>;
  nonce: Buffer;
  reason: string;
  request_hash: string;
  row_count: number;
  scope_hash: string;
}

export interface AuditIntegrityChecks {
  actual_digest_sha256: string;
  check_id: Generated<string>;
  checked_at: Generated<Timestamp>;
  checked_by_account_id: string;
  correlation_id: string;
  expected_digest_sha256: string;
  idempotency_key: string;
  matched: boolean;
  reason: string;
  summary_id: string;
}

export interface AuditIntegritySummaries {
  correlation_id: string;
  digest_sha256: string;
  event_count: Int8;
  generated_at: Generated<Timestamp>;
  generated_by_account_id: string;
  idempotency_key: string;
  previous_digest_sha256: string | null;
  range_ended_at: Timestamp;
  range_started_at: Timestamp;
  reason: string;
  summary_id: Generated<string>;
}

export interface AuditMaintenanceRuns {
  actor_account_id: string;
  completed_at: Timestamp;
  correlation_id: string;
  expired_export_count: number;
  idempotency_key: string;
  reason: string;
  request_hash: string;
  run_id: Generated<string>;
  started_at: Timestamp;
}

export interface AuditRejectedPayloads {
  action: string;
  actor_account_id: string | null;
  actor_subject_hash: string | null;
  correlation_id: string;
  occurred_at: Generated<Timestamp>;
  payload_hash: string;
  rejection_code: string;
  rejection_id: Generated<string>;
  source_context: string;
}

export interface DB {
  "audit.event_facts": AuditEventFacts;
  "audit.evidence_events": AuditEvidenceEvents;
  "audit.export_artifacts": AuditExportArtifacts;
  "audit.integrity_checks": AuditIntegrityChecks;
  "audit.integrity_summaries": AuditIntegritySummaries;
  "audit.maintenance_runs": AuditMaintenanceRuns;
  "audit.rejected_payloads": AuditRejectedPayloads;
}
