/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface IntegrationConsumerReceipts {
  consumer_key: string;
  event_id: string;
  outcome: Generated<string>;
  processed_at: Generated<Timestamp>;
}

export interface IntegrationOutboxEvents {
  aggregate_id: string;
  aggregate_type: string;
  aggregate_version: Int8 | null;
  available_at: Generated<Timestamp>;
  causation_id: string | null;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  event_id: Generated<string>;
  event_type: string;
  /**
   * Version of the named domain event payload.
   */
  event_version: Generated<number>;
  idempotency_key: string;
  last_error_at: Timestamp | null;
  last_error_code: string | null;
  occurred_at: Timestamp;
  payload: Json;
  publish_attempts: Generated<number>;
  published_at: Timestamp | null;
  /**
   * Version of the shared envelope contract, not the domain event payload.
   */
  schema_version: Generated<number>;
  source_context: string;
}

export interface DB {
  "integration.consumer_receipts": IntegrationConsumerReceipts;
  "integration.outbox_events": IntegrationOutboxEvents;
}
