/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MediaAssets {
  asset_id: Generated<string>;
  attribution_text: string | null;
  byte_size: Int8;
  content_sha256: string;
  copyright_text: string | null;
  created_at: Generated<Timestamp>;
  creator: string | null;
  eligibility_status: string;
  license: string | null;
  media_type: string;
  metadata: Generated<Json>;
  object_version: string | null;
  rights_status: string;
  source_id: string | null;
  storage_bucket: string;
  storage_etag: string | null;
  storage_key: string;
  taken_at: Timestamp | null;
  title: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MediaDerivatives {
  derivative_asset_id: string;
  derivative_kind: string;
  parent_asset_id: string;
  transform_metadata: Generated<Json>;
}

export interface MediaPandaAssets {
  asset_id: string;
  display_order: Generated<number>;
  panda_id: string;
  usage_role: Generated<string>;
}

export interface MediaPipelineAssetExportV1 {
  asset_id: string | null;
  attribution_text: string | null;
  byte_size: Int8 | null;
  content_sha256: string | null;
  copyright_text: string | null;
  creator: string | null;
  eligibility_status: string | null;
  license: string | null;
  media_type: string | null;
  pandas: Json | null;
  rights_status: string | null;
  source_id: string | null;
  storage_bucket: string | null;
  storage_key: string | null;
  taken_at: Timestamp | null;
  title: string | null;
  updated_at: Timestamp | null;
}

export interface DB {
  "media.assets": MediaAssets;
  "media.derivatives": MediaDerivatives;
  "media.panda_assets": MediaPandaAssets;
  "media.pipeline_asset_export_v1": MediaPipelineAssetExportV1;
}
