/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PlaceInstitutions {
  country_code: string | null;
  created_at: Generated<Timestamp>;
  institution_id: Generated<string>;
  name_en: string | null;
  name_zh: string | null;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface PlacePlaces {
  boundary: string | null;
  center: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  institution_id: string | null;
  name_en: string | null;
  name_zh: string | null;
  place_id: Generated<string>;
  place_type: string;
  region: string | null;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "place.institutions": PlaceInstitutions;
  "place.places": PlacePlaces;
}
