/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface LineageParentageAssertions {
  assertion_id: string;
  child_id: string;
  created_at: Generated<Timestamp>;
  parent_id: string;
  parent_role: string;
  reviewed_at: Timestamp | null;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface LineageParentageAssertionSources {
  assertion_id: string;
  source_id: string;
}

export interface DB {
  "lineage.parentage_assertion_sources": LineageParentageAssertionSources;
  "lineage.parentage_assertions": LineageParentageAssertions;
}
