/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PandaExternalIdentifiers {
  created_at: Generated<Timestamp>;
  external_identifier_id: Generated<string>;
  normalized_value: string;
  panda_id: string;
  system: string;
  value: string;
}

export interface PandaExternalIdentifierSources {
  external_identifier_id: string;
  source_id: string;
}

export interface PandaFactAssertions {
  assertion_id: string;
  certainty: string;
  created_at: Generated<Timestamp>;
  field_key: string;
  last_verified_on: string;
  lifecycle_state: Generated<string>;
  panda_id: string;
  supersedes_assertion_id: string | null;
  value_json: Json;
}

export interface PandaFactAssertionSources {
  assertion_id: string;
  source_id: string;
  stance: Generated<string>;
}

export interface PandaFactConclusionAssertions {
  assertion_id: string;
  conclusion_id: string;
}

export interface PandaFactConclusions {
  candidate_values_json: Generated<Json>;
  conclusion_id: Generated<string>;
  conclusion_version: number;
  created_at: Generated<Timestamp>;
  field_key: string;
  is_current: Generated<boolean>;
  last_verified_on: string;
  panda_id: string;
  status: string;
  superseded_values_json: Generated<Json>;
  value_json: Json | null;
}

export interface PandaNames {
  created_at: Generated<Timestamp>;
  is_primary: Generated<boolean>;
  language_tag: string;
  name_id: Generated<string>;
  name_kind: string;
  normalized_value: string;
  panda_id: string;
  valid_from: string | null;
  valid_to: string | null;
  value: string;
}

export interface PandaNameSources {
  name_id: string;
  source_id: string;
}

export interface PandaPandas {
  created_at: Generated<Timestamp>;
  panda_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PandaSlugs {
  created_at: Generated<Timestamp>;
  panda_id: string;
  slug: string;
  slug_id: Generated<string>;
  slug_kind: string;
  valid_from: string | null;
  valid_to: string | null;
}

export interface DB {
  "panda.external_identifier_sources": PandaExternalIdentifierSources;
  "panda.external_identifiers": PandaExternalIdentifiers;
  "panda.fact_assertion_sources": PandaFactAssertionSources;
  "panda.fact_assertions": PandaFactAssertions;
  "panda.fact_conclusion_assertions": PandaFactConclusionAssertions;
  "panda.fact_conclusions": PandaFactConclusions;
  "panda.name_sources": PandaNameSources;
  "panda.names": PandaNames;
  "panda.pandas": PandaPandas;
  "panda.slugs": PandaSlugs;
}
