/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PublicationCurrentRelease {
  release_id: string;
  singleton: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface PublicationDeliveryControlEvents {
  action: string;
  actor_account_id: string | null;
  actor_system_key: string | null;
  control_event_id: Generated<string>;
  control_kind: string;
  occurred_at: Generated<Timestamp>;
  reason: string;
  release_id: string | null;
  resource_id: string | null;
  resource_kind: string | null;
}

export interface PublicationReleaseMemberships {
  created_at: Generated<Timestamp>;
  projection_sha256: string;
  release_id: string;
  resource_id: string;
  resource_kind: string;
  source_revision: string;
  source_sha256: string;
  source_version: string;
}

export interface PublicationReleases {
  built_at: Generated<Timestamp>;
  content_sha256: string | null;
  created_at: Generated<Timestamp>;
  created_by_account_id: string | null;
  created_by_system_key: string | null;
  lifecycle_state: Generated<string>;
  projection_schema_version: Generated<number>;
  release_id: Generated<string>;
  sealed_at: Timestamp | null;
  version: string;
}

export interface PublicationReleaseTransitions {
  actor_account_id: string | null;
  actor_system_key: string | null;
  from_release_id: string | null;
  occurred_at: Generated<Timestamp>;
  reason: string;
  release_id: string;
  transition_id: Generated<string>;
  transition_type: string;
}

export interface DB {
  "publication.current_release": PublicationCurrentRelease;
  "publication.delivery_control_events": PublicationDeliveryControlEvents;
  "publication.release_memberships": PublicationReleaseMemberships;
  "publication.release_transitions": PublicationReleaseTransitions;
  "publication.releases": PublicationReleases;
}
