/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/me/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["provisionCurrentAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentProfile"];
        put: operations["replaceCurrentProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitContribution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOwnContributions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/contributions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnContribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/contributions/{submissionId}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerContributionAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/curation/change-sets/{changeSetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurationChangeSet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/curation/change-sets/{changeSetId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateCurationChangeSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/curation/change-sets/{changeSetId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveCurationChangeSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openReviewCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/cases/{reviewCaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReviewCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/cases/{reviewCaseId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimReviewCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/cases/{reviewCaseId}/source-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyReviewSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/cases/{reviewCaseId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideReviewCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/cases/{reviewCaseId}/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recommendReviewCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/moderation/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getModerationAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/moderation/accounts/{accountId}/sanctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applyModerationSanction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/moderation/sanctions/{sanctionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreModerationSanction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/moderation/appeals/{appealCaseId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideModerationAppeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/moderation/appeals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitModerationAppeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/favorites/{pandaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["favoritePanda"];
        delete: operations["unfavoritePanda"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCollections"];
        put?: never;
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/collections/{collectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCollection"];
        options?: never;
        head?: never;
        patch: operations["renameCollection"];
        trace?: never;
    };
    "/api/v2/me/collections/{collectionId}/pandas/{pandaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addPandaToCollection"];
        delete: operations["removePandaFromCollection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCheckins"];
        put?: never;
        post: operations["createCheckin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/checkins/{checkinId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCheckin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/seen-pandas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSeenPandas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/seen-pandas/{pandaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSeenPanda"];
        put: operations["saveSeenPanda"];
        post?: never;
        delete: operations["deleteSeenPanda"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/games/random-panda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRandomPanda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/games/guess/question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGuessQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/games/guess/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["answerGuessQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/game-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGameAttempts"];
        put?: never;
        post: operations["saveGameAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active public release */
        get: operations["getCurrentPublicRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/pandas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pandas from one active release */
        get: operations["listPublicPandas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/pandas/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a release-pinned public panda detail */
        get: operations["getPublicPanda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List places from one active release */
        get: operations["listPublicPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/places/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one public place from the active release */
        get: operations["getPublicPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List lineage assertions from one active release */
        get: operations["listPublicLineage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/residencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List panda residencies from one active release */
        get: operations["listPublicResidencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/life-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List panda life events from one active release */
        get: operations["listPublicLifeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/evidence/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public-safe evidence metadata */
        get: operations["getPublicEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sealed-release public projection counts */
        get: operations["getPublicStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a V2 public release lifecycle record */
        get: operations["getPublicationRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a release-scoped public projection */
        post: operations["buildPublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/seal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seal a built release immutably */
        post: operations["sealPublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically activate a newer sealed release */
        post: operations["activatePublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically reactivate an older compatible sealed release */
        post: operations["rollbackPublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply emergency whole-release suspension */
        post: operations["suspendPublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a suspended release */
        post: operations["restorePublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/resources/takedown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a narrow emergency resource takedown */
        post: operations["takeDownPublicationResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/resources/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an emergency-taken-down resource */
        post: operations["restorePublicationResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List asynchronously projected publication updates */
        get: operations["listUpdates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in account notification inbox */
        get: operations["listMyNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/notifications/{messageId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark one inbox item read */
        patch: operations["markMyNotificationRead"];
        trace?: never;
    };
    "/api/v2/me/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark every unread inbox item read */
        patch: operations["markAllMyNotificationsRead"];
        trace?: never;
    };
    "/api/v2/me/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List effective notification preferences */
        get: operations["listMyNotificationPreferences"];
        /** Set one notification channel preference */
        put: operations["setMyNotificationPreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/privacy/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an asynchronous privacy request */
        post: operations["createMyPrivacyRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/privacy/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one privacy request state */
        get: operations["getMyPrivacyRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/privacy/requests/{requestId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a completed, unexpired privacy export snapshot */
        get: operations["getMyPrivacyExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/audit/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List selected append-only V2 audit evidence */
        get: operations["listAuditEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProvisionedAccountDto: {
            /** Format: uuid */
            accountId: string;
            /** @enum {string} */
            state: "active";
            capabilities: string[];
        };
        CurrentAccountDto: {
            /** Format: uuid */
            accountId: string;
            /** @enum {string} */
            aal: "aal1" | "aal2";
            capabilities: string[];
        };
        FanProfileDto: {
            /** Format: uuid */
            accountId: string;
            nickname: string;
            bio: string;
        };
        ReplaceProfileDto: {
            nickname: string;
            bio: string;
        };
        ContributionAssertionDto: {
            assertionKey: string;
            fieldKey: string;
            value: string | number | boolean | unknown[] | {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            certainty: "confirmed" | "provisional";
            /** Format: date */
            lastVerifiedOn: string;
            sourceKeys: string[];
        };
        ContributionSourceDto: {
            sourceKey: string;
            /** @enum {string} */
            sourceKind: "url" | "publication" | "document" | "other";
            title: string;
            locator: string;
            publisher?: string;
            /** Format: date */
            publishedOn?: string;
        };
        SubmitContributionDto: {
            /** @enum {string} */
            submissionType: "correction" | "sourced_information";
            /** Format: uuid */
            targetPandaId: string;
            publicVersionSeen: string;
            assertions: components["schemas"]["ContributionAssertionDto"][];
            sources: components["schemas"]["ContributionSourceDto"][];
        };
        ContributionRecordDto: {
            /** Format: uuid */
            submissionId: string;
            /** @enum {string} */
            submissionType: "correction" | "sourced_information";
            /** Format: uuid */
            targetPandaId: string;
            publicVersionSeen: string;
            revisionNumber: number;
            status: string;
            /** Format: date-time */
            submittedAt: string;
        };
        ContributionListDto: {
            items: components["schemas"]["ContributionRecordDto"][];
        };
        RegisterContributionAttachmentDto: {
            storageObjectKey: string;
            objectVersion: string;
            originalFilename: string;
            /** @enum {string} */
            mediaType: "application/pdf" | "image/jpeg" | "image/png" | "image/webp";
            byteSize: number;
            contentSha256: string;
        };
        ContributionAttachmentDto: {
            /** Format: uuid */
            attachmentId: string;
            mediaType: string;
            byteSize: number;
            state: string;
        };
        CurationChangeDto: {
            /** Format: uuid */
            changeId: string;
            assertionKey: string;
            fieldKey: string;
            value: string | number | boolean | unknown[] | {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            certainty: "confirmed" | "provisional";
            /** Format: date */
            lastVerifiedOn: string;
            sourceIds: string[];
            /** Format: uuid */
            appliedAssertionId?: string;
        };
        CurationChangeSetDto: {
            /** Format: uuid */
            changeSetId: string;
            /** Format: uuid */
            reviewCaseId: string;
            /** Format: uuid */
            decisionId: string;
            /** Format: uuid */
            submissionId: string;
            revisionNumber: number;
            /** Format: uuid */
            targetPandaId: string;
            /** @enum {string} */
            state: "draft" | "validated" | "approved" | "applied" | "rejected";
            version: number;
            reason: string;
            /** Format: uuid */
            createdByAccountId: string;
            /** Format: uuid */
            validatedByAccountId?: string;
            /** Format: uuid */
            approvedByAccountId?: string;
            changes: components["schemas"]["CurationChangeDto"][];
        };
        ApproveCurationDto: {
            reason: string;
        };
        OpenReviewCaseDto: {
            /** Format: uuid */
            submissionId: string;
        };
        ReviewCaseDto: {
            /** Format: uuid */
            reviewCaseId: string;
            /** Format: uuid */
            submissionId: string;
            revisionNumber: number;
            state: string;
            version: number;
            /** Format: uuid */
            primaryAssigneeId?: string;
        };
        VerifyReviewSourceDto: {
            /** Format: uuid */
            sourceId: string;
            /** @enum {string} */
            outcome: "verified" | "rejected";
            normalizedLocator?: string;
            canonicalSourceId?: string;
            reason: string;
        };
        ReviewVerificationResultDto: {
            /** @enum {boolean} */
            verified: true;
        };
        RecordReviewDecisionDto: {
            /** @enum {string} */
            outcome: "accepted" | "not_accepted" | "duplicate" | "out_of_scope" | "abuse";
            selectedAssertionKeys: string[];
            userVisibleExplanation: string;
            internalReason?: string;
            /** Format: uuid */
            duplicateOfReviewCaseId?: string;
        };
        ReviewDecisionResultDto: {
            /** @enum {boolean} */
            decided: true;
        };
        RecommendReviewDto: {
            reason: string;
        };
        ReviewRecommendationDto: {
            /** Format: uuid */
            changeSetId: string;
        };
        ModerationSubjectDto: {
            /** Format: uuid */
            accountId: string;
            version: number;
            submissionRestricted: boolean;
            attachmentRestricted: boolean;
            notificationRestricted: boolean;
            accountSuspended: boolean;
            accountClosedForAbuse: boolean;
            repeatAbuseCount: number;
        };
        ModerationSanctionDto: {
            /** Format: uuid */
            sanctionId: string;
            /** Format: uuid */
            accountId: string;
            /** @enum {string} */
            kind: "warning" | "submission_restricted" | "attachment_restricted" | "notification_restricted" | "account_suspended" | "account_closed_for_abuse";
            reasonCode: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ModerationAccountDto: {
            subject: components["schemas"]["ModerationSubjectDto"];
            sanctions: components["schemas"]["ModerationSanctionDto"][];
        };
        ApplySanctionDto: {
            /** @enum {string} */
            kind: "warning" | "submission_restricted" | "attachment_restricted" | "notification_restricted" | "account_suspended" | "account_closed_for_abuse";
            reasonCode: string;
            internalExplanation: string;
            userVisibleExplanation: string;
            /** Format: date-time */
            endsAt?: string;
            idempotencyKey: string;
        };
        RestoreSanctionDto: {
            reasonCode: string;
            internalExplanation: string;
            userVisibleExplanation: string;
            idempotencyKey: string;
        };
        RestoredSanctionDto: {
            /** @enum {boolean} */
            restored: true;
        };
        DecideAppealDto: {
            /** @enum {string} */
            outcome: "upheld" | "modified" | "overturned" | "dismissed";
            internalExplanation: string;
            userVisibleExplanation: string;
        };
        ModerationAppealDecisionDto: {
            /** Format: uuid */
            decisionId: string;
            /** Format: uuid */
            appealCaseId: string;
            /** @enum {string} */
            outcome: "upheld" | "modified" | "overturned" | "dismissed";
            /** Format: uuid */
            decidedByAccountId: string;
        };
        SubmitAppealDto: {
            /** Format: uuid */
            sanctionId: string;
            userStatement: string;
        };
        ModerationAppealDto: {
            /** Format: uuid */
            appealCaseId: string;
            /** Format: uuid */
            accountId: string;
            /** Format: uuid */
            sanctionId: string;
            /** @enum {string} */
            state: "open" | "under_review" | "closed";
            version: number;
            userStatement: string;
        };
        FavoriteDto: {
            /** Format: uuid */
            pandaId: string;
            /** Format: date-time */
            favoritedAt: string;
        };
        FavoriteListDto: {
            items: components["schemas"]["FavoriteDto"][];
        };
        UnfavoriteDto: {
            /** Format: uuid */
            pandaId: string;
            /** @enum {boolean} */
            favorited: false;
            favoritedAt: null;
        };
        CollectionDto: {
            /** Format: uuid */
            collectionId: string;
            name: string;
            pandaIds: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CollectionListDto: {
            items: components["schemas"]["CollectionDto"][];
        };
        CollectionNameDto: {
            name: string;
        };
        DeletedCollectionDto: {
            /** Format: uuid */
            collectionId: string;
            /** @enum {boolean} */
            deleted: true;
        };
        CheckinDto: {
            /** Format: uuid */
            checkinId: string;
            /** Format: uuid */
            placeId: string;
            /** Format: date */
            visitedOn: string;
            note?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CheckinListDto: {
            items: components["schemas"]["CheckinDto"][];
        };
        CreateCheckinDto: {
            /** Format: uuid */
            placeId: string;
            /** Format: date */
            visitedOn: string;
            note?: string | null;
        };
        DeletedCheckinDto: {
            /** Format: uuid */
            checkinId: string;
            /** @enum {boolean} */
            deleted: true;
        };
        SeenPandaDto: {
            /** Format: uuid */
            seenId: string;
            /** Format: uuid */
            pandaId: string;
            /** Format: date */
            seenOn?: string | null;
            /** Format: uuid */
            placeId?: string | null;
            note?: string | null;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SeenPandaListDto: {
            items: components["schemas"]["SeenPandaDto"][];
        };
        SaveSeenPandaDto: {
            /** Format: date */
            seenOn?: string | null;
            /** Format: uuid */
            placeId?: string | null;
            note?: string | null;
        };
        DeletedSeenPandaDto: {
            /** Format: uuid */
            pandaId: string;
            /** @enum {boolean} */
            deleted: true;
        };
        RandomPandaDto: {
            /** Format: uuid */
            pandaId: string;
        };
        GuessQuestionDto: {
            /** Format: uuid */
            questionId: string;
            /** Format: uuid */
            mediaAssetId: string;
            /** @enum {string} */
            difficulty: "easy" | "medium" | "hard";
            optionPandaIds: string[];
        };
        GuessAnswerDto: {
            /** Format: uuid */
            questionId: string;
            /** Format: uuid */
            selectedPandaId: string;
        };
        GuessResultDto: {
            correct: boolean;
            /** Format: uuid */
            answerPandaId: string;
            recognitionTips: string[];
        };
        GameAttemptDto: {
            /** Format: uuid */
            attemptId: string;
            /** Format: uuid */
            questionId: string;
            /** Format: uuid */
            selectedPandaId: string;
            correct: boolean;
            /** Format: date-time */
            attemptedAt: string;
        };
        GameAttemptListDto: {
            items: components["schemas"]["GameAttemptDto"][];
        };
        SavedGameAttemptDto: {
            attempt: components["schemas"]["GameAttemptDto"];
            answer: components["schemas"]["GuessResultDto"];
        };
        PublicReadReleaseDto: {
            /** Format: uuid */
            releaseId: string;
            version: string;
        };
        PublicPandaNameDto: {
            languageTag: string;
            nameKind: string;
            value: string;
            isPrimary: boolean;
        };
        PublicPandaFactDto: {
            fieldKey: string;
            value?: string | number | boolean | unknown[] | {
                [key: string]: unknown;
            } | null;
            status: string;
            /** Format: date */
            lastVerifiedOn: string;
            conclusionVersion: number;
        };
        PublicPandaSummaryDto: {
            /** Format: uuid */
            pandaId: string;
            canonicalSlug: string;
            legacySlugs: string[];
            names: components["schemas"]["PublicPandaNameDto"][];
            facts: components["schemas"]["PublicPandaFactDto"][];
        };
        PublicPandaListDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            items: components["schemas"]["PublicPandaSummaryDto"][];
        };
        PublicLineageSummaryDto: {
            assertionId: string;
            /** Format: uuid */
            childId: string;
            /** Format: uuid */
            parentId: string;
            /** @enum {string} */
            parentRole: "father" | "mother";
            sourceIds: string[];
        };
        PublicResidencySummaryDto: {
            residencyId: string;
            /** Format: uuid */
            pandaId: string;
            /** Format: uuid */
            placeId: string;
            residencyType: string;
            /** Format: date */
            startOn?: string;
            startPrecision: string;
            /** Format: date */
            endOn?: string;
            endPrecision?: string;
            status: string;
            sourceIds: string[];
        };
        PublicLifeEventSummaryDto: {
            eventId: string;
            eventType: string;
            eventStatus: string;
            /** Format: date */
            occurredOn?: string;
            occurredPrecision: string;
            /** Format: uuid */
            fromPlaceId?: string;
            /** Format: uuid */
            toPlaceId?: string;
            summary?: string;
            participantIds: string[];
            sourceIds: string[];
        };
        PublicMediaSummaryDto: {
            /** Format: uuid */
            assetId: string;
            /** Format: uuid */
            pandaId: string;
            sourceId?: string;
            usageRole: string;
            displayOrder: number;
            objectKey: string;
            contentSha256: string;
            mediaType: string;
            title?: string;
            creator?: string;
            copyrightText?: string;
            license?: string;
            attributionText?: string;
            /** Format: date-time */
            takenAt?: string;
        };
        PublicEvidenceSummaryDto: {
            sourceId: string;
            publisher: string;
            title: string;
            /** Format: uri */
            url: string;
            /** Format: date */
            publishedOn?: string;
            /** Format: date */
            lastVerifiedOn: string;
            languageTag: string;
            accessState: string;
            evidenceTier?: string;
            publicSummary?: string;
        };
        PublicPandaDetailDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            panda: components["schemas"]["PublicPandaSummaryDto"];
            lineage: components["schemas"]["PublicLineageSummaryDto"][];
            residencies: components["schemas"]["PublicResidencySummaryDto"][];
            events: components["schemas"]["PublicLifeEventSummaryDto"][];
            media: components["schemas"]["PublicMediaSummaryDto"][];
            evidence: components["schemas"]["PublicEvidenceSummaryDto"][];
        };
        PublicPlaceSummaryDto: {
            /** Format: uuid */
            placeId: string;
            /** Format: uuid */
            institutionId?: string;
            slug: string;
            placeType: string;
            nameZh?: string;
            nameEn?: string;
            countryCode?: string;
            region?: string;
            longitude?: number;
            latitude?: number;
        };
        PublicPlaceListDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            items: components["schemas"]["PublicPlaceSummaryDto"][];
        };
        PublicPlaceDetailDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            place: components["schemas"]["PublicPlaceSummaryDto"];
        };
        PublicLineageListDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            items: components["schemas"]["PublicLineageSummaryDto"][];
        };
        PublicResidencyListDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            items: components["schemas"]["PublicResidencySummaryDto"][];
        };
        PublicLifeEventListDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            items: components["schemas"]["PublicLifeEventSummaryDto"][];
        };
        PublicEvidenceDetailDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            source: components["schemas"]["PublicEvidenceSummaryDto"];
        };
        PublicStatsDto: {
            pandaCount: number;
            institutionCount: number;
            placeCount: number;
            lineageCount: number;
            residencyCount: number;
            lifeEventCount: number;
            mediaCount: number;
            evidenceSourceCount: number;
        };
        PublicStatsResponseDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            stats: components["schemas"]["PublicStatsDto"];
        };
        PublicReleaseDto: {
            /** Format: uuid */
            releaseId: string;
            version: string;
            projectionSchemaVersion: number;
            /** @enum {string} */
            lifecycleState: "building" | "sealed";
            /** Format: date-time */
            builtAt: string;
            /** Format: date-time */
            sealedAt?: string;
            contentSha256?: string;
        };
        BuildPublicReleaseDto: {
            /** @example 2026.08.27.1 */
            version: string;
        };
        PublicationReasonDto: {
            reason: string;
        };
        PublicationResourceControlDto: {
            reason: string;
            /** @enum {string} */
            resourceKind: "panda" | "place" | "media" | "evidence";
            resourceId: string;
        };
        UpdateTargetDto: {
            /** @enum {string} */
            resourceKind: "panda" | "institution" | "place" | "lineage" | "residency" | "life_event" | "media" | "evidence";
            resourceId: string;
            /** @enum {string} */
            changeType: "added" | "changed" | "removed";
        };
        UpdateItemDto: {
            /** Format: uuid */
            updateId: string;
            /** @enum {string} */
            updateType: "release_activated" | "release_rolled_back";
            /** Format: uuid */
            releaseId: string;
            /** Format: uuid */
            previousReleaseId?: string;
            releaseVersion: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            publishedAt: string;
            targets: components["schemas"]["UpdateTargetDto"][];
        };
        NotificationMessageDto: {
            /** Format: uuid */
            messageId: string;
            /** @enum {string} */
            category: "knowledge_update" | "correction";
            content: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            seenAt: string | null;
            /** Format: date-time */
            readAt: string | null;
        };
        NotificationBulkReadResultDto: {
            updatedCount: number;
        };
        NotificationPreferenceDto: {
            /** @enum {string} */
            category: "knowledge_update" | "correction";
            /** @enum {string} */
            channel: "station" | "email";
            enabled: boolean;
            version: number;
            /** Format: date-time */
            updatedAt: string | null;
        };
        NotificationPreferenceInputDto: {
            /** @enum {string} */
            category: "knowledge_update" | "correction";
            /** @enum {string} */
            channel: "station" | "email";
            enabled: boolean;
        };
        CreatePrivacyRequestDto: {
            /** @enum {string} */
            kind: "access_export" | "account_deletion";
            reason: string;
            /** Format: uuid */
            idempotencyKey: string;
        };
        PrivacyRequestDto: {
            /** Format: uuid */
            requestId: string;
            /** @enum {string} */
            kind: "access_export" | "account_deletion";
            /** @enum {string} */
            state: "pending" | "processing" | "completed" | "failed";
            reason: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            failedAt?: string;
            failureCode?: string;
        };
        PrivacyExportDto: {
            /** Format: uuid */
            requestId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            payload: {
                [key: string]: unknown;
            };
        };
        AuditEvidenceDto: {
            /** Format: uuid */
            sourceEventId: string;
            sourceContext: string;
            eventType: string;
            aggregateType: string;
            aggregateId: string;
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            occurredAt: string;
            payloadSha256: string;
            /** Format: date-time */
            recordedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    provisionCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionedAccountDto"];
                };
            };
        };
    };
    getCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentAccountDto"];
                };
            };
        };
    };
    getCurrentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FanProfileDto"];
                };
            };
        };
    };
    replaceCurrentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FanProfileDto"];
                };
            };
        };
    };
    submitContribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitContributionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionRecordDto"];
                };
            };
        };
    };
    listOwnContributions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionListDto"];
                };
            };
        };
    };
    getOwnContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionRecordDto"];
                };
            };
        };
    };
    registerContributionAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterContributionAttachmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionAttachmentDto"];
                };
            };
        };
    };
    getCurationChangeSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                changeSetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationChangeSetDto"];
                };
            };
        };
    };
    validateCurationChangeSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                changeSetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationChangeSetDto"];
                };
            };
        };
    };
    approveCurationChangeSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                changeSetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveCurationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationChangeSetDto"];
                };
            };
        };
    };
    openReviewCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenReviewCaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCaseDto"];
                };
            };
        };
    };
    getReviewCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewCaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCaseDto"];
                };
            };
        };
    };
    claimReviewCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewCaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCaseDto"];
                };
            };
        };
    };
    verifyReviewSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewCaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyReviewSourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewVerificationResultDto"];
                };
            };
        };
    };
    decideReviewCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewCaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordReviewDecisionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDecisionResultDto"];
                };
            };
        };
    };
    recommendReviewCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewCaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRecommendationDto"];
                };
            };
        };
    };
    getModerationAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationAccountDto"];
                };
            };
        };
    };
    applyModerationSanction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplySanctionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationSanctionDto"];
                };
            };
        };
    };
    restoreModerationSanction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sanctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreSanctionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoredSanctionDto"];
                };
            };
        };
    };
    decideModerationAppeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appealCaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideAppealDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationAppealDecisionDto"];
                };
            };
        };
    };
    submitModerationAppeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAppealDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationAppealDto"];
                };
            };
        };
    };
    listFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteListDto"];
                };
            };
        };
    };
    favoritePanda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pandaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteDto"];
                };
            };
        };
    };
    unfavoritePanda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pandaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnfavoriteDto"];
                };
            };
        };
    };
    listCollections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListDto"];
                };
            };
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionNameDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDto"];
                };
            };
        };
    };
    deleteCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedCollectionDto"];
                };
            };
        };
    };
    renameCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionNameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDto"];
                };
            };
        };
    };
    addPandaToCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                pandaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDto"];
                };
            };
        };
    };
    removePandaFromCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                pandaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDto"];
                };
            };
        };
    };
    listCheckins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinListDto"];
                };
            };
        };
    };
    createCheckin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckinDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinDto"];
                };
            };
        };
    };
    deleteCheckin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkinId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedCheckinDto"];
                };
            };
        };
    };
    listSeenPandas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeenPandaListDto"];
                };
            };
        };
    };
    getSeenPanda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pandaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeenPandaDto"];
                };
            };
        };
    };
    saveSeenPanda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pandaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSeenPandaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeenPandaDto"];
                };
            };
        };
    };
    deleteSeenPanda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pandaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedSeenPandaDto"];
                };
            };
        };
    };
    getRandomPanda: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RandomPandaDto"];
                };
            };
        };
    };
    getGuessQuestion: {
        parameters: {
            query?: {
                difficulty?: "easy" | "medium" | "hard";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuessQuestionDto"];
                };
            };
        };
    };
    answerGuessQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuessAnswerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuessResultDto"];
                };
            };
        };
    };
    listGameAttempts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameAttemptListDto"];
                };
            };
        };
    };
    saveGameAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuessAnswerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedGameAttemptDto"];
                };
            };
        };
    };
    getCurrentPublicRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReadReleaseDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicPandas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPandaListDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicPanda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPandaDetailDto"];
                };
            };
            /** @description The panda is absent or under emergency takedown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicPlaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPlaceListDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPlaceDetailDto"];
                };
            };
            /** @description The place is absent or under emergency takedown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicLineage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicLineageListDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicResidencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicResidencyListDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicLifeEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicLifeEventListDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEvidenceDetailDto"];
                };
            };
            /** @description The evidence source is absent or under emergency takedown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStatsResponseDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
            /** @description The release does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buildPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildPublicReleaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
        };
    };
    sealPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
            /** @description The release does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The release has no publishable membership yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activatePublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
            /** @description The release is not a valid forward activation target. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rollbackPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
            /** @description The release is not a valid rollback target. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suspendPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
        };
    };
    restorePublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
        };
    };
    takeDownPublicationResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationResourceControlDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restorePublicationResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationResourceControlDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUpdates: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateItemDto"][];
                };
            };
        };
    };
    listMyNotifications: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationMessageDto"][];
                };
            };
        };
    };
    markMyNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationMessageDto"];
                };
            };
        };
    };
    markAllMyNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationBulkReadResultDto"];
                };
            };
        };
    };
    listMyNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferenceDto"][];
                };
            };
        };
    };
    setMyNotificationPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferenceInputDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferenceDto"];
                };
            };
        };
    };
    createMyPrivacyRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrivacyRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyRequestDto"];
                };
            };
        };
    };
    getMyPrivacyRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyRequestDto"];
                };
            };
        };
    };
    getMyPrivacyExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyExportDto"];
                };
            };
        };
    };
    listAuditEvidence: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvidenceDto"][];
                };
            };
        };
    };
}
