/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active public release */
        get: operations["getCurrentPublicRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/pandas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pandas from one active release */
        get: operations["listPublicPandas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/pandas/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a release-pinned public panda detail */
        get: operations["getPublicPanda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List places from one active release */
        get: operations["listPublicPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/places/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one public place from the active release */
        get: operations["getPublicPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/evidence/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public-safe evidence metadata */
        get: operations["getPublicEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sealed-release public projection counts */
        get: operations["getPublicStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a V2 public release lifecycle record */
        get: operations["getPublicationRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a release-scoped public projection */
        post: operations["buildPublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/seal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seal a built release immutably */
        post: operations["sealPublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically activate a newer sealed release */
        post: operations["activatePublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically reactivate an older compatible sealed release */
        post: operations["rollbackPublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply emergency whole-release suspension */
        post: operations["suspendPublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/releases/{releaseId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a suspended release */
        post: operations["restorePublicationRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/resources/takedown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a narrow emergency resource takedown */
        post: operations["takeDownPublicationResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/publication/resources/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an emergency-taken-down resource */
        post: operations["restorePublicationResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicReadReleaseDto: {
            /** Format: uuid */
            releaseId: string;
            version: string;
        };
        PublicPandaNameDto: {
            languageTag: string;
            nameKind: string;
            value: string;
            isPrimary: boolean;
        };
        PublicPandaFactDto: {
            fieldKey: string;
            value?: string | number | boolean | unknown[] | {
                [key: string]: unknown;
            } | null;
            status: string;
            /** Format: date */
            lastVerifiedOn: string;
            conclusionVersion: number;
        };
        PublicPandaSummaryDto: {
            /** Format: uuid */
            pandaId: string;
            canonicalSlug: string;
            legacySlugs: string[];
            names: components["schemas"]["PublicPandaNameDto"][];
            facts: components["schemas"]["PublicPandaFactDto"][];
        };
        PublicPandaListDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            items: components["schemas"]["PublicPandaSummaryDto"][];
        };
        PublicLineageSummaryDto: {
            assertionId: string;
            /** Format: uuid */
            childId: string;
            /** Format: uuid */
            parentId: string;
            /** @enum {string} */
            parentRole: "father" | "mother";
            sourceIds: string[];
        };
        PublicResidencySummaryDto: {
            residencyId: string;
            /** Format: uuid */
            pandaId: string;
            /** Format: uuid */
            placeId: string;
            residencyType: string;
            /** Format: date */
            startOn?: string;
            startPrecision: string;
            /** Format: date */
            endOn?: string;
            endPrecision?: string;
            status: string;
            sourceIds: string[];
        };
        PublicLifeEventSummaryDto: {
            eventId: string;
            eventType: string;
            eventStatus: string;
            /** Format: date */
            occurredOn?: string;
            occurredPrecision: string;
            /** Format: uuid */
            fromPlaceId?: string;
            /** Format: uuid */
            toPlaceId?: string;
            summary?: string;
            participantIds: string[];
            sourceIds: string[];
        };
        PublicMediaSummaryDto: {
            /** Format: uuid */
            assetId: string;
            /** Format: uuid */
            pandaId: string;
            sourceId?: string;
            usageRole: string;
            displayOrder: number;
            objectKey: string;
            contentSha256: string;
            mediaType: string;
            title?: string;
            creator?: string;
            copyrightText?: string;
            license?: string;
            attributionText?: string;
            /** Format: date-time */
            takenAt?: string;
        };
        PublicEvidenceSummaryDto: {
            sourceId: string;
            publisher: string;
            title: string;
            /** Format: uri */
            url: string;
            /** Format: date */
            publishedOn?: string;
            /** Format: date */
            lastVerifiedOn: string;
            languageTag: string;
            accessState: string;
            evidenceTier?: string;
            publicSummary?: string;
        };
        PublicPandaDetailDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            panda: components["schemas"]["PublicPandaSummaryDto"];
            lineage: components["schemas"]["PublicLineageSummaryDto"][];
            residencies: components["schemas"]["PublicResidencySummaryDto"][];
            events: components["schemas"]["PublicLifeEventSummaryDto"][];
            media: components["schemas"]["PublicMediaSummaryDto"][];
            evidence: components["schemas"]["PublicEvidenceSummaryDto"][];
        };
        PublicPlaceSummaryDto: {
            /** Format: uuid */
            placeId: string;
            /** Format: uuid */
            institutionId?: string;
            slug: string;
            placeType: string;
            nameZh?: string;
            nameEn?: string;
            countryCode?: string;
            region?: string;
            longitude?: number;
            latitude?: number;
        };
        PublicPlaceListDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            items: components["schemas"]["PublicPlaceSummaryDto"][];
        };
        PublicPlaceDetailDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            place: components["schemas"]["PublicPlaceSummaryDto"];
        };
        PublicEvidenceDetailDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            source: components["schemas"]["PublicEvidenceSummaryDto"];
        };
        PublicStatsDto: {
            pandaCount: number;
            institutionCount: number;
            placeCount: number;
            lineageCount: number;
            residencyCount: number;
            lifeEventCount: number;
            mediaCount: number;
            evidenceSourceCount: number;
        };
        PublicStatsResponseDto: {
            release: components["schemas"]["PublicReadReleaseDto"];
            stats: components["schemas"]["PublicStatsDto"];
        };
        PublicReleaseDto: {
            /** Format: uuid */
            releaseId: string;
            version: string;
            projectionSchemaVersion: number;
            /** @enum {string} */
            lifecycleState: "building" | "sealed";
            /** Format: date-time */
            builtAt: string;
            /** Format: date-time */
            sealedAt?: string;
            contentSha256?: string;
        };
        BuildPublicReleaseDto: {
            /** @example 2026.08.27.1 */
            version: string;
        };
        PublicationReasonDto: {
            reason: string;
        };
        PublicationResourceControlDto: {
            reason: string;
            /** @enum {string} */
            resourceKind: "panda" | "place" | "media" | "evidence";
            resourceId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentPublicRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReadReleaseDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicPandas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPandaListDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicPanda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPandaDetailDto"];
                };
            };
            /** @description The panda is absent or under emergency takedown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicPlaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPlaceListDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPlaceDetailDto"];
                };
            };
            /** @description The place is absent or under emergency takedown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEvidenceDetailDto"];
                };
            };
            /** @description The evidence source is absent or under emergency takedown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStatsResponseDto"];
                };
            };
            /** @description No active deliverable release is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
            /** @description The release does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buildPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildPublicReleaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
        };
    };
    sealPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
            /** @description The release does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The release has no publishable membership yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activatePublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
            /** @description The release is not a valid forward activation target. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rollbackPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
            /** @description The release is not a valid rollback target. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suspendPublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
        };
    };
    restorePublicationRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationReasonDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReleaseDto"];
                };
            };
        };
    };
    takeDownPublicationResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationResourceControlDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restorePublicationResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationResourceControlDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
