from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

ROOT = Path(__file__).resolve().parents[2]
VAULT_DIR = ROOT / "data" / "local-panda-research"
SOURCES_PATH = VAULT_DIR / "sources.jsonl"
OUTPUT_PATH = VAULT_DIR / "records" / "2026-07-25-official-followup.jsonl"
COLLECTED_AT = "2026-07-25T00:00:00+08:00"


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8-sig") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if line:
                value = json.loads(line)
                if isinstance(value, dict):
                    rows.append(value)
    return rows


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(canonical_json(row) + "\n" for row in rows),
        encoding="utf-8",
        newline="",
    )


def source(
    source_id: str,
    *,
    publisher: str,
    title: str,
    url: str,
    language: str,
    region: str,
    notes: str,
) -> dict[str, Any]:
    return {
        "source_id": source_id,
        "publisher": publisher,
        "title": title,
        "url": url,
        "language": language,
        "region": region,
        "source_type": "institution_primary",
        "authority": "primary",
        "access_mode": "manual_review",
        "automated_collection": "not_reviewed",
        "rights_status": "facts_only_no_media_reuse",
        "retrieved_at": COLLECTED_AT,
        "notes": notes,
    }


SOURCES = [
    source(
        "src-sdzwa-harmony-black-white-2024",
        publisher="San Diego Zoo Wildlife Alliance",
        title="Harmony in Black and White",
        url="https://sandiegozoowildlifealliance.org/story-hub/2024/06/26/harmony-in-black-and-white",
        language="en",
        region="United States",
        notes="Official history covering Bai Yun, Gao Gao, Mei Sheng and later San Diego-born siblings.",
    ),
    source(
        "src-sdzwa-panda-family-update-2016",
        publisher="San Diego Zoo Wildlife Alliance",
        title="Update on Our Panda Family",
        url="https://sandiegozoowildlifealliance.org/story-hub/2016/02/22/update-on-our-panda-family",
        language="en",
        region="United States and China",
        notes="Official update on Mei Sheng and other San Diego-born pandas after their return to China.",
    ),
    source(
        "src-everland-natural-birth-2020",
        publisher="Samsung C&T Newsroom",
        title="Everland Succeeds in Natural Birth of Giant Panda",
        url="https://news.samsungcnt.com/en/features/resort/2020-07-everland-succeeds-natural-birth-giant-panda/",
        language="en",
        region="South Korea",
        notes="Official account of Ai Bao and Le Bao's arrival, reproductive preparation and Fu Bao's birth.",
    ),
    source(
        "src-everland-le-bao-personality-2024",
        publisher="Samsung C&T Newsroom",
        title="Keeping Up with the Bao Family: Everland's Adorable Pandas Are Full of Charm and Personality",
        url="https://news.samsungcnt.com/en/features/resort/2024-10-keeping-up-with-the-bao-family-everlands-adorable-pandas-are-full-of-charm-and-personality/",
        language="en",
        region="South Korea",
        notes="Official Bao-family personality profiles, including Le Bao's temperament and humorous behaviour.",
    ),
    source(
        "src-everland-new-cub-birth-2026",
        publisher="Samsung C&T Newsroom",
        title="Everland Welcomes New Baby Panda as Panda Conservation Research Marks 10 Years",
        url="https://news.samsungcnt.com/en/features/resort/2026-06-everland-welcomes-new-baby-panda-as-panda-conservation-research-marks-10-years/",
        language="en",
        region="South Korea",
        notes="Official birth announcement with time, sex, weight, parents, natural mating and monitoring methods.",
    ),
    source(
        "src-everland-new-cub-three-weeks-2026",
        publisher="Samsung C&T Newsroom",
        title="Everland Reveals New Photos of Baby Panda at Three Weeks Old",
        url="https://news.samsungcnt.com/en/features/resort/2026-06-everland-reveals-new-photos-of-baby-panda-at-three-weeks-old/",
        language="en",
        region="South Korea",
        notes="Official 21-day growth, health, appearance and care update for the 2026 female cub.",
    ),
    source(
        "src-everland-new-cub-naming-contest-2026",
        publisher="Samsung C&T Newsroom",
        title="Everland Opens Public Naming Contest for the Youngest Panda Cub",
        url="https://news.samsungcnt.com/ko/%EC%A0%84%EC%B2%B4%EA%B8%B0%EC%82%AC/%EB%A6%AC%EC%A1%B0%ED%8A%B8%EB%B6%80%EB%AC%B8/2026-07-%ED%8C%90%EB%8B%A4-%EA%B0%80%EC%A1%B1-%EB%A7%89%EB%82%B4-%EC%9D%B4%EB%A6%84-%EC%A7%80%EC%96%B4%EC%A3%BC%EC%84%B8%EC%9A%94-%EC%97%90%EB%B2%84%EB%9E%9C%EB%93%9C-%EB%A7%89%EB%91%A5%EC%9D%B4/",
        language="ko",
        region="South Korea",
        notes="Official July 13 naming-contest status and one-month growth update; no final name asserted.",
    ),
    source(
        "src-everland-twins-independence-2025",
        publisher="Samsung C&T Newsroom",
        title="Everland's Twin Pandas Say Goodbye to Mom and Take Their First Steps Toward Independence",
        url="https://news.samsungcnt.com/en/features/resort/2025-08-everlands-twin-pandas-say-goodbye-to-mom-and-take-their-first-steps-toward-independence/",
        language="en",
        region="South Korea",
        notes="Official independence timeline, training and viewing schedule for Rui Bao and Hui Bao.",
    ),
    source(
        "src-everland-panda-second-house-2025",
        publisher="Samsung C&T Newsroom",
        title="Twin Pandas Rui Bao and Hui Bao Move Into Everland's New Panda Second House",
        url="https://news.samsungcnt.com/en/features/resort/2025-10-twin-pandas-rui-bao-and-hui-bao-move-into-everlands-new-panda-second-house/",
        language="en",
        region="South Korea",
        notes="Official opening and facility details for Rui Bao and Hui Bao's independent residence.",
    ),
    source(
        "src-everland-winter-bao-family-2026",
        publisher="Samsung C&T Newsroom",
        title="Everland Launches Winter Good Morning Bao Family Program at Panda World",
        url="https://news.samsungcnt.com/en/features/resort/2026-01-everland-launches-winter-good-morning-bao-family-program-at-panda-world/",
        language="en",
        region="South Korea",
        notes="Official winter weights and observed morning behaviour for Rui Bao and Hui Bao.",
    ),
    source(
        "src-everland-twins-second-birthday-2025",
        publisher="Samsung C&T Newsroom",
        title="Bamboo, Cake, and Goodbyes: A Final Birthday Bash for Everland's Twin Pandas",
        url="https://news.samsungcnt.com/en/features/resort/2025-07-bamboo-cake-and-goodbyes-a-final-birthday-bash-for-everlands-twin-pandas/",
        language="en",
        region="South Korea",
        notes="Official birthday dates, bamboo celebration and custom badge enrichment for the Bao family.",
    ),
]


def record(
    record_id: str,
    *,
    subject_type: str,
    subject_id: str,
    subject_label: str,
    category: str,
    predicate: str,
    value: Any,
    source_id: str,
    source_locator: str,
    source_language: str,
    summary_zh: str,
    tags: list[str],
) -> dict[str, Any]:
    return {
        "record_id": record_id,
        "subject": {"type": subject_type, "id": subject_id, "label": subject_label},
        "category": category,
        "predicate": predicate,
        "value": value,
        "source_id": source_id,
        "source_locator": source_locator,
        "source_language": source_language,
        "summary_zh": summary_zh,
        "evidence_level": "direct",
        "confidence": "high",
        "review_status": "captured",
        "publication_status": "local_only",
        "collected_at": COLLECTED_AT,
        "tags": tags,
    }


RECORDS = [
    record(
        "lpr-20260725-official-0001",
        subject_type="panda",
        subject_id="mei-sheng",
        subject_label="Mei Sheng",
        category="sex",
        predicate="sex",
        value="male",
        source_id="src-sdzwa-harmony-black-white-2024",
        source_locator="San Diego-born cub summary",
        source_language="en",
        summary_zh="圣迭戈动物园官方资料将美生记为雄性大熊猫。",
        tags=["mei-sheng", "san-diego", "sex"],
    ),
    record(
        "lpr-20260725-official-0002",
        subject_type="panda",
        subject_id="mei-sheng",
        subject_label="Mei Sheng",
        category="birth",
        predicate="birth_year",
        value=2003,
        source_id="src-sdzwa-harmony-black-white-2024",
        source_locator="San Diego-born cub summary",
        source_language="en",
        summary_zh="美生于2003年在圣迭戈出生。",
        tags=["mei-sheng", "birth", "san-diego-born"],
    ),
    record(
        "lpr-20260725-official-0003",
        subject_type="panda",
        subject_id="mei-sheng",
        subject_label="Mei Sheng",
        category="relationship",
        predicate="parents",
        value={"father_id": "gao-gao", "father_label": "Gao Gao", "mother_id": "bai-yun", "mother_label": "Bai Yun"},
        source_id="src-sdzwa-harmony-black-white-2024",
        source_locator="Gao Gao and Bai Yun offspring chronology",
        source_language="en",
        summary_zh="美生的父亲是高高，母亲是白云。",
        tags=["mei-sheng", "lineage", "parents"],
    ),
    record(
        "lpr-20260725-official-0004",
        subject_type="panda",
        subject_id="mei-sheng",
        subject_label="Mei Sheng",
        category="relationship",
        predicate="younger_siblings",
        value=[
            {"id": "su-lin", "label": "Su Lin", "birth_year": 2005},
            {"id": "zhen-zhen", "label": "Zhen Zhen", "birth_year": 2007},
            {"id": "yun-zi", "label": "Yun Zi", "birth_year": 2009},
            {"id": "xiao-liwu", "label": "Xiao Liwu", "birth_year": 2012},
        ],
        source_id="src-sdzwa-harmony-black-white-2024",
        source_locator="Later Gao Gao and Bai Yun cubs",
        source_language="en",
        summary_zh="美生之后，高高和白云又育有苏琳、珍珍、云子和小礼物。",
        tags=["mei-sheng", "siblings", "lineage"],
    ),
    record(
        "lpr-20260725-official-0005",
        subject_type="panda",
        subject_id="mei-sheng",
        subject_label="Mei Sheng",
        category="transfer",
        predicate="returned_to_china",
        value={"status": True, "destination_country": "China"},
        source_id="src-sdzwa-harmony-black-white-2024",
        source_locator="San Diego-born pandas returned to China",
        source_language="en",
        summary_zh="美生与圣迭戈后来出生的兄弟姐妹均已返回中国。",
        tags=["mei-sheng", "return-to-china", "transfer"],
    ),
    record(
        "lpr-20260725-official-0006",
        subject_type="panda",
        subject_id="mei-sheng",
        subject_label="Mei Sheng",
        category="location",
        predicate="documented_location_2016",
        value={"year": 2016, "institution": "Dujiangyan giant panda base", "country": "China"},
        source_id="src-sdzwa-panda-family-update-2016",
        source_locator="Mei Sheng update",
        source_language="en",
        summary_zh="2016年官方回访记录显示，美生生活在都江堰大熊猫基地。",
        tags=["mei-sheng", "dujiangyan", "location"],
    ),
    record(
        "lpr-20260725-official-0007",
        subject_type="panda",
        subject_id="mei-sheng",
        subject_label="Mei Sheng",
        category="health",
        predicate="condition_in_2016_update",
        value={"condition": "reported in great shape", "housing": "comfortable in a large enclosure"},
        source_id="src-sdzwa-panda-family-update-2016",
        source_locator="Mei Sheng update",
        source_language="en",
        summary_zh="2016年回访时，美生被描述为状态很好，并已适应宽敞圈舍。",
        tags=["mei-sheng", "health", "welfare", "2016"],
    ),
    record(
        "lpr-20260725-official-0008",
        subject_type="panda_family",
        subject_id="everland-ai-bao-le-bao",
        subject_label="Ai Bao and Le Bao",
        category="transfer",
        predicate="arrival_at_everland",
        value={"date_precision": "month", "date": "2016-03", "origin": "Dujiangyan, Sichuan", "destination": "Everland Panda World"},
        source_id="src-everland-natural-birth-2020",
        source_locator="Pair arrival and adaptation history",
        source_language="en",
        summary_zh="爱宝和乐宝于2016年3月从四川都江堰来到韩国爱宝乐园熊猫世界。",
        tags=["everland", "ai-bao", "le-bao", "transfer"],
    ),
    record(
        "lpr-20260725-official-0009",
        subject_type="panda_family",
        subject_id="everland-ai-bao-le-bao",
        subject_label="Ai Bao and Le Bao",
        category="husbandry_training",
        predicate="pre_breeding_management",
        value=["room and scent exchange", "nutritional support", "blood and urine hormone analysis", "continuous health monitoring"],
        source_id="src-everland-natural-birth-2020",
        source_locator="Natural breeding preparation",
        source_language="en",
        summary_zh="为促进自然繁殖，饲养团队进行圈舍与气味交换、营养支持、血液和尿液激素分析及持续健康监测。",
        tags=["everland", "reproduction", "husbandry", "hormone-monitoring"],
    ),
    record(
        "lpr-20260725-official-0010",
        subject_type="panda",
        subject_id="fu-bao",
        subject_label="Fu Bao",
        category="birth",
        predicate="birth_datetime",
        value={"date": "2020-07-20", "time": "21:49", "place": "Everland Panda World"},
        source_id="src-everland-natural-birth-2020",
        source_locator="First Korea-born cub birth details",
        source_language="en",
        summary_zh="福宝于2020年7月20日21时49分在爱宝乐园熊猫世界出生。",
        tags=["fu-bao", "birth", "everland"],
    ),
    record(
        "lpr-20260725-official-0011",
        subject_type="panda_family",
        subject_id="everland-ai-bao-le-bao",
        subject_label="Ai Bao and Le Bao",
        category="reproduction",
        predicate="first_natural_birth_success",
        value={"cub_id": "fu-bao", "date": "2020-07-20", "method": "natural breeding"},
        source_id="src-everland-natural-birth-2020",
        source_locator="Natural birth result",
        source_language="en",
        summary_zh="爱宝与乐宝于2020年自然繁育出福宝，这是韩国首只本土出生的大熊猫。",
        tags=["everland", "natural-breeding", "fu-bao"],
    ),
    record(
        "lpr-20260725-official-0012",
        subject_type="panda",
        subject_id="le-bao",
        subject_label="Le Bao",
        category="personality",
        predicate="official_personality_description",
        value=["strong personality", "humorous antics"],
        source_id="src-everland-le-bao-personality-2024",
        source_locator="Le Bao profile",
        source_language="en",
        summary_zh="爱宝乐园官方将乐宝描述为个性鲜明，并常有幽默有趣的举动。",
        tags=["le-bao", "personality", "fun-fact"],
    ),
    record(
        "lpr-20260725-official-0013",
        subject_type="panda",
        subject_id="le-bao",
        subject_label="Le Bao",
        category="alias",
        predicate="official_profile_nickname",
        value="The Loving Panda Dad",
        source_id="src-everland-le-bao-personality-2024",
        source_locator="Le Bao profile heading",
        source_language="en",
        summary_zh="乐宝在官方家庭介绍中被称为“充满爱意的熊猫爸爸”。",
        tags=["le-bao", "nickname", "personality"],
    ),
    record(
        "lpr-20260725-official-0014",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="birth",
        predicate="birth_datetime",
        value={"date": "2026-06-03", "time": "10:53", "place": "Everland Panda World"},
        source_id="src-everland-new-cub-birth-2026",
        source_locator="Birth announcement",
        source_language="en",
        summary_zh="爱宝乐园2026年雌性幼崽于2026年6月3日10时53分出生。",
        tags=["everland", "2026-cub", "birth"],
    ),
    record(
        "lpr-20260725-official-0015",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="sex",
        predicate="sex",
        value="female",
        source_id="src-everland-new-cub-birth-2026",
        source_locator="Birth announcement",
        source_language="en",
        summary_zh="2026年爱宝乐园新生幼崽为雌性。",
        tags=["everland", "2026-cub", "sex"],
    ),
    record(
        "lpr-20260725-official-0016",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="growth_measurement",
        predicate="birth_weight_grams",
        value=171,
        source_id="src-everland-new-cub-birth-2026",
        source_locator="Birth weight",
        source_language="en",
        summary_zh="该幼崽出生体重为171克。",
        tags=["everland", "2026-cub", "birth-weight"],
    ),
    record(
        "lpr-20260725-official-0017",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="relationship",
        predicate="parents_and_sisters",
        value={
            "father_id": "le-bao",
            "father_label": "Le Bao",
            "mother_id": "ai-bao",
            "mother_label": "Ai Bao",
            "older_sister_ids": ["fu-bao", "rui-bao", "hui-bao"],
        },
        source_id="src-everland-new-cub-birth-2026",
        source_locator="Bao family relationship summary",
        source_language="en",
        summary_zh="该幼崽的父亲是乐宝、母亲是爱宝，姐姐为福宝、睿宝和辉宝。",
        tags=["everland", "2026-cub", "lineage", "siblings"],
    ),
    record(
        "lpr-20260725-official-0018",
        subject_type="panda_family",
        subject_id="everland-ai-bao-le-bao",
        subject_label="Ai Bao and Le Bao",
        category="reproduction",
        predicate="natural_mating_2026",
        value={"month": "2026-02", "resulting_cub_id": "everland-cub-2026"},
        source_id="src-everland-new-cub-birth-2026",
        source_locator="Breeding and pregnancy monitoring section",
        source_language="en",
        summary_zh="爱宝和乐宝于2026年2月自然交配，随后诞生2026年雌性幼崽。",
        tags=["everland", "natural-mating", "2026-cub"],
    ),
    record(
        "lpr-20260725-official-0019",
        subject_type="research_programme",
        subject_id="everland-panda-conservation-research",
        subject_label="Everland panda conservation research",
        category="research",
        predicate="pregnancy_monitoring_methods",
        value=["behaviour monitoring", "blood hormone analysis", "urine hormone analysis", "health examinations"],
        source_id="src-everland-new-cub-birth-2026",
        source_locator="Pregnancy monitoring methods",
        source_language="en",
        summary_zh="爱宝乐园通过行为观察、血液与尿液激素分析和健康检查判断大熊猫妊娠变化。",
        tags=["everland", "research", "reproduction", "hormones"],
    ),
    record(
        "lpr-20260725-official-0020",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="growth_measurement",
        predicate="weight_at_21_days_grams",
        value={"age_days": 21, "date": "2026-06-23", "weight_grams": 670},
        source_id="src-everland-new-cub-three-weeks-2026",
        source_locator="21-day health examination",
        source_language="en",
        summary_zh="幼崽在出生第21天体重达到670克，约为出生体重的四倍。",
        tags=["everland", "2026-cub", "growth", "21-days"],
    ),
    record(
        "lpr-20260725-official-0021",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="appearance",
        predicate="black_markings_visible_at_21_days",
        value=["eyes", "ears", "shoulders", "arms", "legs"],
        source_id="src-everland-new-cub-three-weeks-2026",
        source_locator="Appearance in three-week photographs",
        source_language="en",
        summary_zh="出生21天时，幼崽眼周、耳朵、肩部、前肢和腿部的黑色斑纹已经明显。",
        tags=["everland", "2026-cub", "appearance", "development"],
    ),
    record(
        "lpr-20260725-official-0022",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="health",
        predicate="health_status_at_21_days",
        value={"cub": "healthy", "mother_ai_bao": "healthy", "care": "around-the-clock"},
        source_id="src-everland-new-cub-three-weeks-2026",
        source_locator="Health and care update",
        source_language="en",
        summary_zh="出生21天时幼崽与母亲爱宝均健康，饲养员、兽医和中方专家持续24小时照护。",
        tags=["everland", "2026-cub", "health", "maternal-care"],
    ),
    record(
        "lpr-20260725-official-0023",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="growth_measurement",
        predicate="weight_at_one_month_kilograms",
        value={"age": "slightly over one month", "weight_kilograms": 1.4, "multiple_of_birth_weight": "over 8"},
        source_id="src-everland-new-cub-naming-contest-2026",
        source_locator="Early July health examination",
        source_language="ko",
        summary_zh="幼崽出生一个多月后体重约1.4千克，已超过出生体重的八倍。",
        tags=["everland", "2026-cub", "growth", "one-month"],
    ),
    record(
        "lpr-20260725-official-0024",
        subject_type="panda",
        subject_id="everland-cub-2026",
        subject_label="Everland 2026 female cub",
        category="milestone",
        predicate="public_naming_contest_opened",
        value={"date": "2026-07-13", "status": "public suggestions open; final official name not asserted in source"},
        source_id="src-everland-new-cub-naming-contest-2026",
        source_locator="Naming contest announcement",
        source_language="ko",
        summary_zh="截至2026年7月13日，爱宝乐园已开放公众征名；该来源没有公布正式名字，因此本地档案仍使用临时ID。",
        tags=["everland", "2026-cub", "naming", "unresolved-name"],
    ),
    record(
        "lpr-20260725-official-0025",
        subject_type="panda_family",
        subject_id="everland-rui-hui-twins",
        subject_label="Rui Bao and Hui Bao",
        category="milestone",
        predicate="separated_from_mother_for_independence",
        value={"last_public_day_with_mother": "2025-08-12", "independent_schedule_started": "2025-08-13", "mother_id": "ai-bao"},
        source_id="src-everland-twins-independence-2025",
        source_locator="Independence transition timeline",
        source_language="en",
        summary_zh="睿宝和辉宝在2025年8月12日最后一次与母亲爱宝共同公开活动，并从8月13日起进入独立生活安排。",
        tags=["rui-bao", "hui-bao", "independence", "ai-bao"],
    ),
    record(
        "lpr-20260725-official-0026",
        subject_type="panda_family",
        subject_id="everland-rui-hui-twins",
        subject_label="Rui Bao and Hui Bao",
        category="husbandry_training",
        predicate="independence_training",
        value={"purpose": "gradual self-reliance before maternal separation", "period": "months before August 2025"},
        source_id="src-everland-twins-independence-2025",
        source_locator="Preparing for Independence",
        source_language="en",
        summary_zh="在与母亲分开前，睿宝和辉宝接受了数月的渐进式独立训练。",
        tags=["rui-bao", "hui-bao", "husbandry", "independence-training"],
    ),
    record(
        "lpr-20260725-official-0027",
        subject_type="institution",
        subject_id="everland-panda-second-house",
        subject_label="Panda Second House",
        category="milestone",
        predicate="opened",
        value={"date": "2025-10-03", "area_square_metres": 1200, "resident_ids": ["rui-bao", "hui-bao"]},
        source_id="src-everland-panda-second-house-2025",
        source_locator="Facility opening summary",
        source_language="en",
        summary_zh="爱宝乐园面积约1200平方米的熊猫第二馆于2025年10月3日开放，供睿宝和辉宝独立生活。",
        tags=["everland", "facility", "rui-bao", "hui-bao"],
    ),
    record(
        "lpr-20260725-official-0028",
        subject_type="panda_family",
        subject_id="everland-rui-hui-twins",
        subject_label="Rui Bao and Hui Bao",
        category="growth_measurement",
        predicate="weight_by_january_2026",
        value={"each_weight_kilograms": "over 70", "reported_at": "2026-01"},
        source_id="src-everland-winter-bao-family-2026",
        source_locator="Winter programme twins update",
        source_language="en",
        summary_zh="截至2026年1月，睿宝和辉宝的体重均已超过70千克。",
        tags=["rui-bao", "hui-bao", "growth", "weight"],
    ),
    record(
        "lpr-20260725-official-0029",
        subject_type="panda_family",
        subject_id="everland-rui-hui-twins",
        subject_label="Rui Bao and Hui Bao",
        category="behaviour",
        predicate="winter_morning_behaviour",
        value=["rolling", "running", "playing outdoors"],
        source_id="src-everland-winter-bao-family-2026",
        source_locator="Observed winter morning routines",
        source_language="en",
        summary_zh="冬季清晨活动中，睿宝和辉宝会在户外翻滚、奔跑和玩耍。",
        tags=["rui-bao", "hui-bao", "behaviour", "winter"],
    ),
    record(
        "lpr-20260725-official-0030",
        subject_type="panda_family",
        subject_id="everland-bao-family-birthdays",
        subject_label="Everland Bao family birthdays",
        category="milestone",
        predicate="july_birthdays",
        value=[
            {"subject_id": "rui-bao", "month_day": "07-07"},
            {"subject_id": "hui-bao", "month_day": "07-07"},
            {"subject_id": "ai-bao", "month_day": "07-13"},
            {"subject_id": "fu-bao", "month_day": "07-20"},
            {"subject_id": "le-bao", "month_day": "07-28"},
        ],
        source_id="src-everland-twins-second-birthday-2025",
        source_locator="Happy Bao's Day birthday calendar",
        source_language="en",
        summary_zh="爱宝乐园官方生日月资料列出：睿宝和辉宝7月7日、爱宝7月13日、福宝7月20日、乐宝7月28日生日。",
        tags=["everland", "birthdays", "bao-family", "july"],
    ),
    record(
        "lpr-20260725-official-0031",
        subject_type="panda_family",
        subject_id="everland-rui-hui-twins",
        subject_label="Rui Bao and Hui Bao",
        category="enrichment",
        predicate="second_birthday_enrichment",
        value=["bamboo cake", "flower birthday displays", "custom employee badges engraved with names and faces"],
        source_id="src-everland-twins-second-birthday-2025",
        source_locator="Second birthday celebration",
        source_language="en",
        summary_zh="睿宝和辉宝两岁生日活动包括竹子蛋糕、花艺生日装置，以及刻有名字和头像的定制员工徽章。",
        tags=["rui-bao", "hui-bao", "birthday", "enrichment"],
    ),
]


def merge_sources() -> int:
    existing = load_jsonl(SOURCES_PATH)
    by_id = {str(row.get("source_id") or ""): row for row in existing}
    added = 0
    for row in SOURCES:
        source_id = row["source_id"]
        if source_id not in by_id:
            added += 1
        by_id[source_id] = row
    ordered_ids = [str(row.get("source_id") or "") for row in existing]
    for row in SOURCES:
        if row["source_id"] not in ordered_ids:
            ordered_ids.append(row["source_id"])
    write_jsonl(SOURCES_PATH, [by_id[source_id] for source_id in ordered_ids if source_id])
    return added


def main() -> int:
    added_sources = merge_sources()
    write_jsonl(OUTPUT_PATH, RECORDS)
    print(
        "Official panda follow-up ingestion passed: "
        f"sources={len(SOURCES)} ({added_sources} newly added), records={len(RECORDS)}, "
        f"output={OUTPUT_PATH.relative_to(ROOT)}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
